table 'Activity Distribution Measures LL'
	lineageTag: fca402bb-cc47-4d48-a026-3a2058954462

	measure 'Activity by Application' =
			
			SWITCH(
			    SELECTEDVALUE('Activity Distribution Measures LL'[Application]),
			    "Teams", [Total Teams Activity],
			    "Outlook", [Total Email Activity],
			    "Word", [Total Word Activity],
			    "Excel", [Total Excel Activity],
			    "PowerPoint", [Total PPT Activity],
			    BLANK()
			)
		formatString: 0
		lineageTag: c56a84c6-cdbc-4ba6-9807-0b8d7700b35f

	measure 'DEBUG Priority Distribution' = ```
			
			VAR Critical = COUNTROWS(FILTER(SecDemEntraUsers, 
			    [Selected App M365 Tier Label] = "Top 10%" && [Selected App Copilot Tier Label] = "Bottom 50%"))
			VAR High = COUNTROWS(FILTER(SecDemEntraUsers, 
			    ([Selected App M365 Tier Label] = "Top 10%" && [Selected App Copilot Tier Label] = "25-50%") ||
			    ([Selected App M365 Tier Label] = "10-25%" && [Selected App Copilot Tier Label] = "Bottom 50%")))
			VAR Medium = COUNTROWS(FILTER(SecDemEntraUsers, 
			    ([Selected App M365 Tier Label] = "Top 10%" && [Selected App Copilot Tier Label] = "10-25%") ||
			    ([Selected App M365 Tier Label] = "10-25%" && [Selected App Copilot Tier Label] = "25-50%") ||
			    ([Selected App M365 Tier Label] = "25-50%" && [Selected App Copilot Tier Label] = "Bottom 50%")))
			VAR Promoter = COUNTROWS(FILTER(SecDemEntraUsers, 
			    [Selected App Copilot Tier Label] = "Top 10%" ||
			    ([Selected App M365 Tier Label] = "Bottom 50%" && [Selected App Copilot Tier Label] = "10-25%")))
			VAR Total = COUNTROWS(FILTER(SecDemEntraUsers, 
			    NOT(ISBLANK([Selected App M365 Tier Label])) && NOT(ISBLANK([Selected App Copilot Tier Label]))))
			VAR Low = Total - Critical - High - Medium - Promoter
			
			RETURN
			"C:" & Critical & " H:" & High & " M:" & Medium & " P:" & Promoter & " L:" & Low & " T:" & Total
			```
		isHidden
		lineageTag: 2cde2a27-1a21-46e4-adf2-674b92fc61d2

	column Application
		lineageTag: e867b22d-6041-4fbc-a37f-4421031d341c
		summarizeBy: none
		isNameInferred
		sourceColumn: [Application]

		annotation SummarizationSetBy = Automatic

	column Weight
		lineageTag: 5feb2920-6353-4b08-babd-fb6e31dfb73f
		summarizeBy: sum
		isNameInferred
		sourceColumn: [Weight]

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'Activity Distribution Measures LL' = calculated
		mode: import
		source =
				
				DATATABLE(
				    "Application", STRING,
				    "Weight", DOUBLE,
				    {
				        {"Teams", 0.20},
				        {"Outlook", 0.20},
				        {"Word", 0.20},
				        {"Excel", 0.20},
				        {"PowerPoint", 0.20}
				    }
				)

	annotation PBI_Id = 03e8f10b231040bd924d44efbda8b751

