table 'App Selection'
	lineageTag: 896b4e5b-e3cc-4e39-8792-ce1a05e716e1

	measure 'Selected App M365 Activity' =
			
			VAR SelectedApp = SELECTEDVALUE('App Selection'[AppName])
			RETURN
			SWITCH(
			    SelectedApp,
			    "M365 All Apps", [M365 All Apps Total V2],
			    "Teams", [Teams Activity Sum V2],        // TOTAL, not TIER
			    "Outlook", [Outlook Activity Sum V2],    // TOTAL, not TIER
			    "Word", [Word Activity Count v2],          // TOTAL, not TIER
			    "Excel", [Excel Activity Count V2] ,        // TOTAL, not TIER
			    "PowerPoint", [PowerPoint Activity Count V2] ,  // TOTAL, not TIER
			    BLANK()
			)
		lineageTag: 40315885-21e0-4ccc-9797-1185a68ade64

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Selected App M365 Tier Label' = ```
			
			VAR SelectedApp = SELECTEDVALUE('App Selection'[AppName])
			VAR TierValue = SWITCH(
			    SelectedApp,
			    "M365 All Apps", [M365 All Apps Tier V2],
			    "Teams", [Teams Tier v2],
			    "Outlook", [Outlook Tier v2],
			    "Word", [Word Tier V2],
			    "Excel", [Excel Tier V2],
			    "PowerPoint", [PowerPoint Tier V2],
			    BLANK()
			)
			RETURN
			SWITCH(
			    TierValue,
			    1, "Top 10%",
			    2, "10-25%",
			    3, "25-50%",
			    4, "Bottom 50%",
			    BLANK()
			)
			
			```
		lineageTag: 6107f48c-3a79-4e04-9e07-01cd0d7f64d5

	measure 'Selected App Header' =
			
			VAR SelectedApp = SELECTEDVALUE('App Selection'[AppName], "Select App")
			RETURN SelectedApp
		lineageTag: 058184e8-45b4-4593-8f23-71df50b0fdf9

	measure 'Selected App Priority' = ```
			
			VAR M365Tier = [Selected App M365 Tier Label]
			VAR CopilotTier = [Selected App Copilot Tier Label]
			VAR SelectedPriorityFilter = SELECTEDVALUE('Priority Filter'[PriorityName])
			
			VAR Priority = 
			    SWITCH(TRUE(),
			        // CRITICAL
			        M365Tier = "Top 10%" && CopilotTier = "Bottom 50%", "Critical",
			        
			        // HIGH
			        M365Tier = "Top 10%" && CopilotTier = "25-50%", "High",
			        M365Tier = "10-25%" && CopilotTier = "Bottom 50%", "High",
			        
			        // MEDIUM
			        M365Tier = "Top 10%" && CopilotTier = "10-25%", "Medium",
			        M365Tier = "10-25%" && CopilotTier = "25-50%", "Medium",
			        M365Tier = "25-50%" && CopilotTier = "Bottom 50%", "Medium",
			        
			        // PROMOTER
			        M365Tier = "Top 10%" && CopilotTier = "Top 10%", "Promoter",
			        M365Tier = "10-25%" && CopilotTier = "Top 10%", "Promoter",
			        M365Tier = "25-50%" && CopilotTier = "Top 10%", "Promoter",
			        M365Tier = "Bottom 50%" && CopilotTier = "Top 10%", "Promoter",
			        M365Tier = "Bottom 50%" && CopilotTier = "10-25%", "Promoter",
			        
			        // LOW
			        "Low"
			    )
			
			VAR PriorityEmoji = 
			    SWITCH(Priority,
			        "Critical", "🔴 Critical",
			        "High", "🟠 High",
			        "Medium", "🟡 Medium",
			        "Promoter", "🟢 Promoter",
			        "Low", "⚪ Low"
			    )
			
			RETURN
			IF(
			    ISBLANK(SelectedPriorityFilter) || Priority = SelectedPriorityFilter,
			    PriorityEmoji,
			    BLANK()
			)
			```
		lineageTag: 2600aa78-9f1c-41c4-9b5b-b520a6c685b6

	measure 'Selected App Next Action' = ```
			
			VAR Priority = [Selected App Priority]
			RETURN 
			    SWITCH(
			        TRUE(),
			        Priority = "🔴 Critical", "Immediate Training",
			        Priority = "🟠 High", "Immediate Training",
			        Priority = "🟡 Medium", "Train Next",
			        Priority = "🟢 Promoter", "Advanced Training",
			        Priority = "⚪ Low", "Monitor",
			        BLANK()
			    )
			```
		lineageTag: 4350133f-4129-4461-ac6c-4785400a21c0

	measure 'Selected App Priority Icon' = ```
			
			VAR Priority = [Selected App Priority]
			RETURN 
			    SWITCH(
			        Priority,
			        "Critical", "🔴",
			        "High", "🟠",
			        "Medium", "🟡",
			        "Promoter", "🟢",
			        "Low", "⚪",
			        ""
			    )
			```
		lineageTag: 33c028fe-36b3-49b3-be9d-cc79f44cb71e

	measure 'Heatmap Priority' = ```
			
			VAR M365Tier = SELECTEDVALUE('M365 Tiers'[M365TierName])
			VAR CopilotTier = SELECTEDVALUE('Copilot Tiers'[CopilotTierName])
			VAR CopilotTierClean = 
			    SWITCH(
			        CopilotTier,
			        "Top 10 Copilot", "Top 10%",
			        "10-25 Copilot", "10-25%",
			        "25-50 Copilot", "25-50%",
			        "Bottom 50% Copilot", "Bottom 50%",
			        BLANK()
			    )
			VAR Priority = 
			    SWITCH(
			        TRUE(),
			        // CRITICAL: Top M365, no Copilot
			        M365Tier = "Top 10%" && CopilotTierClean = "Bottom 50%", "Critical",
			        
			        // HIGH: Strong M365, weak Copilot
			        M365Tier = "Top 10%" && CopilotTierClean = "25-50%", "High",
			        M365Tier = "10-25%" && CopilotTierClean = "Bottom 50%", "High",
			        
			        // MEDIUM: Moderate opportunity
			        M365Tier = "Top 10%" && CopilotTierClean = "10-25%", "Medium",
			        M365Tier = "10-25%" && CopilotTierClean = "25-50%", "Medium",
			        M365Tier = "25-50%" && CopilotTierClean = "Bottom 50%", "Medium",
			        
			        // PROMOTER: Strong Copilot users
			        M365Tier = "Top 10%" && CopilotTierClean = "Top 10%", "Promoter",
			        M365Tier = "10-25%" && CopilotTierClean = "Top 10%", "Promoter",
			        M365Tier = "25-50%" && CopilotTierClean = "Top 10%", "Promoter",
			        M365Tier = "Bottom 50%" && CopilotTierClean = "Top 10%", "Promoter",
			        M365Tier = "Bottom 50%" && CopilotTierClean = "10-25%", "Promoter",
			        
			        // LOW: Everything else
			        "Low"
			    )
			RETURN
			    SWITCH(
			        Priority,
			        "Critical", "🔴 Critical",
			        "High", "🟠 High",
			        "Medium", "🟡 Medium",
			        "Promoter", "🟢 Promoter",
			        "Low", "⚪ Low",
			        BLANK()
			    )
			```
		lineageTag: ea23a066-8e80-4793-8230-d62cf8d8122e

	measure 'Selected App Action Weighted' =
			
			VAR CurrentTier = SELECTEDVALUE('Copilot Qualification Criteria LL'[Tier])
			RETURN
			    SWITCH(
			        CurrentTier,
			        1, "🔴 Prioritize",
			        2, "🟠 License Next",
			        3, "🟡 Enablement",
			        4, "⚪ Monitor",
			        ""
			    )
		lineageTag: 87e09be2-13fa-461b-a622-e31856619672

	measure 'User Action Weighted' = ```
			
			VAR SelectedApp = SELECTEDVALUE('App Selection'[AppName], "M365 All Apps")
			
			VAR UserTierLabel = 
			    SWITCH(
			        SelectedApp,
			        "Teams", [Teams Percentile Weighted],
			        "Outlook", [Outlook Percentile Weighted],
			        "Word", [Word Percentile Weighted],
			        "Excel", [Excel Percentile Weighted],
			        "PowerPoint", [PowerPoint Percentile Weighted],
			        "M365 All Apps", [M365 All Apps Percentile Weighted],
			        [M365 All Apps Percentile Weighted]
			    )
			
			RETURN
			    SWITCH(
			        UserTierLabel,
			        "Top 10%", "🔴 Prioritize",
			        "10-25%", "🟠 License Next",
			        "25-50%", "🟡 Enablement",
			        "Bottom 50%", "⚪ Monitor",
			        "⚪ Monitor"
			    )
			```
		lineageTag: 0630099b-9782-4c17-a845-50bd4cb5750e

	measure 'Show User Based on App Tier Filter' = ```
			
			VAR SelectedApp = SELECTEDVALUE('App Selection'[AppName], "M365 All Apps")
			VAR HasActionSelection = ISFILTERED('Action Filter'[ActionName])
			
			VAR UserTierLabel = 
			    SWITCH(
			        SelectedApp,
			        "Teams", [Teams Percentile Weighted],
			        "Outlook", [Outlook Percentile Weighted],
			        "Word", [Word Percentile Weighted],
			        "Excel", [Excel Percentile Weighted],
			        "PowerPoint", [PowerPoint Percentile Weighted],
			        "M365 All Apps", [M365 All Apps Percentile Weighted],
			        [M365 All Apps Percentile Weighted]
			    )
			
			VAR UserAction = 
			    SWITCH(
			        UserTierLabel,
			        "Top 10%", "🔴 Prioritize",
			        "10-25%", "🟠 License Next",
			        "25-50%", "🟡 Enablement",
			        "Bottom 50%", "⚪ Monitor",
			        "⚪ Monitor"
			    )
			
			RETURN
			    IF(
			        NOT HasActionSelection,
			        1,
			        IF(UserAction IN VALUES('Action Filter'[ActionName]), 1, 0)
			    )
			```
		formatString: 0
		lineageTag: eea8f253-4114-4004-b0a8-570b3e2a80af

	measure 'User Action by Selected App' = ```
			
			VAR M365Tier = [Selected App M365 Tier Label]
			VAR CopilotTier = [Selected App Copilot Tier Label]
			
			VAR UserPriority = 
			    IF(
			        ISBLANK(M365Tier) || ISBLANK(CopilotTier),
			        "Low",
			        SWITCH(TRUE(),
			            M365Tier = "Top 10%" && CopilotTier = "Bottom 50%", "Critical",
			            M365Tier = "Top 10%" && CopilotTier = "25-50%", "High",
			            M365Tier = "10-25%" && CopilotTier = "Bottom 50%", "High",
			            M365Tier = "Top 10%" && CopilotTier = "10-25%", "Medium",
			            M365Tier = "10-25%" && CopilotTier = "25-50%", "Medium",
			            M365Tier = "25-50%" && CopilotTier = "Bottom 50%", "Medium",
			            M365Tier = "Top 10%" && CopilotTier = "Top 10%", "Promoter",
			            M365Tier = "10-25%" && CopilotTier = "Top 10%", "Promoter",
			            M365Tier = "25-50%" && CopilotTier = "Top 10%", "Promoter",
			            M365Tier = "Bottom 50%" && CopilotTier = "Top 10%", "Promoter",
			            M365Tier = "Bottom 50%" && CopilotTier = "10-25%", "Promoter",
			            "Low"
			        )
			    )
			
			RETURN
			SWITCH(UserPriority,
			    "Critical", "Immediate Training",
			    "High", "Immediate Training",
			    "Medium", "Train Next",
			    "Promoter", "Advanced Training",
			    "Monitor"
			)
			```
		lineageTag: f3bc5441-05e8-4202-8525-a0c2547c6839

	measure 'Show User Based on Action and App' =
			
			VAR HasActionSelection = ISFILTERED('Action Filter'[ActionName])
			VAR UserAction = [User Action by Selected App]
			RETURN
			    IF(
			        NOT HasActionSelection,
			        1,
			        IF(
			            UserAction IN VALUES('Action Filter'[ActionName]),
			            1,
			            0
			        )
			    )
		formatString: 0
		lineageTag: 6824d01c-3267-4930-813b-e1807535c58d

	measure '# of Users by App and Tier' = ```
			
			VAR SelectedApp = SELECTEDVALUE('App Selection'[AppName], "M365 All Apps")
			VAR SelectedTier = SELECTEDVALUE('Copilot Qualification Criteria LL'[Tier])
			VAR TargetLabel = 
			    SWITCH(
			        SelectedTier,
			        1, "Top 10%",
			        2, "10-25%",
			        3, "25-50%",
			        4, "Bottom 50%",
			        ""
			    )
			
			RETURN
			SWITCH(
			    SelectedApp,
			    "M365 All Apps", 
			        COUNTROWS(
			            FILTER(
			                SUMMARIZE('SecDemoM365Usage', 'SecDemoM365Usage'[UserId]),
			                [M365 All Apps Percentile Weighted] = TargetLabel
			            )
			        ),
			    "Teams", 
			        COUNTROWS(
			            FILTER(
			                SUMMARIZE('SecDemoM365Usage', 'SecDemoM365Usage'[UserId]),
			                [Teams Percentile Weighted] = TargetLabel
			            )
			        ),
			    "Outlook", 
			        COUNTROWS(
			            FILTER(
			                SUMMARIZE('SecDemoM365Usage', 'SecDemoM365Usage'[UserId]),
			                [Outlook Percentile Weighted] = TargetLabel
			            )
			        ),
			    "Word", 
			        COUNTROWS(
			            FILTER(
			                SUMMARIZE('SecDemoM365Usage', 'SecDemoM365Usage'[UserId]),
			                [Word Percentile Weighted] = TargetLabel
			            )
			        ),
			    "Excel", 
			        COUNTROWS(
			            FILTER(
			                SUMMARIZE('SecDemoM365Usage', 'SecDemoM365Usage'[UserId]),
			                [Excel Percentile Weighted] = TargetLabel
			            )
			        ),
			    "PowerPoint", 
			        COUNTROWS(
			            FILTER(
			                SUMMARIZE('SecDemoM365Usage', 'SecDemoM365Usage'[UserId]),
			                [PowerPoint Percentile Weighted] = TargetLabel
			            )
			        ),
			    BLANK()
			)
			```
		formatString: 0
		lineageTag: 501d9370-24ec-4f77-ae6f-17d95e9cd525

	measure 'Tier Description by App' = ```
			
			VAR SelectedApp = SELECTEDVALUE('App Selection'[AppName], "M365 All Apps")
			VAR CurrentTier = SELECTEDVALUE('Copilot Qualification Criteria LL'[Tier])
			
			RETURN
			SWITCH(
			    CurrentTier,
			    1, "Top 10% " & SelectedApp & " users",
			    2, "10-25% " & SelectedApp & " users", 
			    3, "25-50% " & SelectedApp & " users",
			    4, "Bottom 50% " & SelectedApp & " users",
			    ""
			)
			```
		lineageTag: 7cf89f51-b91d-474d-b0d3-970d0c3f0ed8

	measure 'Users by Action' = ```
			
			VAR SelectedApp = SELECTEDVALUE('App Selection'[AppName], "M365 All Apps")
			VAR CurrentAction = SELECTEDVALUE('Action Filter'[ActionName])
			VAR ActionWithoutEmoji = 
			    SWITCH(
			        CurrentAction,
			        "🔴 Prioritize", "Prioritize",
			        "🟠 License Next", "License Next",
			        "🟡 Enablement", "Enablement",
			        "⚪ Monitor", "Monitor",
			        CurrentAction
			    )
			
			VAR TargetTier = 
			    SWITCH(
			        ActionWithoutEmoji,
			        "Prioritize", "Top 10%",
			        "License Next", "10-25%",
			        "Enablement", "25-50%",
			        "Monitor", "Bottom 50%",
			        ""
			    )
			
			RETURN
			SWITCH(
			    SelectedApp,
			    "M365 All Apps", 
			        COUNTROWS(
			            FILTER(
			                SUMMARIZE('SecDemoM365Usage', 'SecDemoM365Usage'[UserId]),
			                [M365 All Apps Percentile Weighted] = TargetTier
			            )
			        ),
			    "Teams", 
			        COUNTROWS(
			            FILTER(
			                SUMMARIZE('SecDemoM365Usage', 'SecDemoM365Usage'[UserId]),
			                [Teams Percentile Weighted] = TargetTier
			            )
			        ),
			    "Outlook", 
			        COUNTROWS(
			            FILTER(
			                SUMMARIZE('SecDemoM365Usage', 'SecDemoM365Usage'[UserId]),
			                [Outlook Percentile Weighted] = TargetTier
			            )
			        ),
			    "Word", 
			        COUNTROWS(
			            FILTER(
			                SUMMARIZE('SecDemoM365Usage', 'SecDemoM365Usage'[UserId]),
			                [Word Percentile Weighted] = TargetTier
			            )
			        ),
			    "Excel", 
			        COUNTROWS(
			            FILTER(
			                SUMMARIZE('SecDemoM365Usage', 'SecDemoM365Usage'[UserId]),
			                [Excel Percentile Weighted] = TargetTier
			            )
			        ),
			    "PowerPoint", 
			        COUNTROWS(
			            FILTER(
			                SUMMARIZE('SecDemoM365Usage', 'SecDemoM365Usage'[UserId]),
			                [PowerPoint Percentile Weighted] = TargetTier
			            )
			        ),
			    BLANK()
			)
			```
		formatString: 0
		lineageTag: b543c429-64d1-442e-a0be-4e90dbaf0d90

	column AppName
		lineageTag: e41ca1de-22a9-4776-81d6-bda156234ca2
		summarizeBy: none
		isNameInferred
		sourceColumn: [AppName]
		sortByColumn: SortOrder

		annotation SummarizationSetBy = Automatic

	column SortOrder
		formatString: 0
		lineageTag: 9cebc37e-83f5-45b3-8763-4bef7936da8b
		summarizeBy: sum
		isNameInferred
		sourceColumn: [SortOrder]

		annotation SummarizationSetBy = Automatic

	partition 'App Selection' = calculated
		mode: import
		source =
				
				DATATABLE(
				    "AppName", STRING,
				    "SortOrder", INTEGER,
				    {
				        {"M365 All Apps", 1},
				        {"Teams", 2},
				        {"Outlook", 3},
				        {"Word", 4},
				        {"Excel", 5},
				        {"PowerPoint", 6}
				    }
				)

	annotation PBI_Id = 9a6a69c97f694f34842e3545e87a29b1

