table 'App Activity LL'
	lineageTag: 977578a3-f6c9-49d3-9cfd-3f7639ba37ba

	measure 'Top Tier Activity Value LL' = ```
			
			VAR SelectedApp = SELECTEDVALUE('App Activity LL'[App])
			VAR SelectedActivity = SELECTEDVALUE('App Activity LL'[Activity])
			
			RETURN
			SWITCH(
			    TRUE(),
			    // TEAMS ACTIVITIES
			    SelectedApp = "Teams" && SelectedActivity = "Ad Hoc Meetings Attended",
			        SUMX(
			            RELATEDTABLE('SecDemoM365Usage'),
			            IF(
			                'SecDemoM365Usage'[Workload] = "MicrosoftTeams" &&
			                'SecDemoM365Usage'[Operation] = "MeetingParticipantJoined",
			                1,
			                0
			            )
			        ),
			    SelectedApp = "Teams" && SelectedActivity = "Ad Hoc Meetings Organized",
			        SUMX(
			            RELATEDTABLE('SecDemoM365Usage'),
			            IF(
			                'SecDemoM365Usage'[Workload] = "MicrosoftTeams" &&
			                'SecDemoM365Usage'[Operation] = "MeetingParticipantJoined",
			                1,
			                0
			            )
			        ),
			    SelectedApp = "Teams" && SelectedActivity = "Call",
			        SUMX(
			            RELATEDTABLE('SecDemoM365Usage'),
			            IF(
			                'SecDemoM365Usage'[Workload] = "MicrosoftTeams" &&
			                'SecDemoM365Usage'[Operation] = "MeetingParticipantJoined",
			                1,
			                0
			            )
			        ),
			    SelectedApp = "Teams" && SelectedActivity = "Meeting",
			        SUMX(
			            RELATEDTABLE('SecDemoM365Usage'),
			            IF(
			                'SecDemoM365Usage'[Workload] = "MicrosoftTeams" &&
			                'SecDemoM365Usage'[Operation] = "MeetingParticipantJoined",
			                1,
			                0
			            )
			        ),
			    SelectedApp = "Teams" && SelectedActivity = "Meetings Attended",
			        SUMX(
			            RELATEDTABLE('SecDemoM365Usage'),
			            IF(
			                'SecDemoM365Usage'[Workload] = "MicrosoftTeams" &&
			                'SecDemoM365Usage'[Operation] = "MeetingParticipantJoined",
			                1,
			                0
			            )
			        ),
			    SelectedApp = "Teams" && SelectedActivity = "Meetings Organized",
			        SUMX(
			            RELATEDTABLE('SecDemoM365Usage'),
			            IF(
			                'SecDemoM365Usage'[Workload] = "MicrosoftTeams" &&
			                'SecDemoM365Usage'[Operation] = "MeetingParticipantJoined",
			                1,
			                0
			            )
			        ),
			    SelectedApp = "Teams" && SelectedActivity = "Private Chat Message",
			        SUMX(
			            RELATEDTABLE('SecDemoM365Usage'),
			            IF(
			                'SecDemoM365Usage'[Workload] = "MicrosoftTeams" &&
			                'SecDemoM365Usage'[Operation] IN {"MessageSent", "MessageRead"},
			                1,
			                0
			            )
			        ),
			    SelectedApp = "Teams" && SelectedActivity = "Scheduled One-time Meetings Attended",
			        SUMX(
			            RELATEDTABLE('SecDemoM365Usage'),
			            IF(
			                'SecDemoM365Usage'[Workload] = "MicrosoftTeams" &&
			                'SecDemoM365Usage'[Operation] = "MeetingParticipantJoined",
			                1,
			                0
			            )
			        ),
			    SelectedApp = "Teams" && SelectedActivity = "Scheduled One-time Meetings Organized",
			        SUMX(
			            RELATEDTABLE('SecDemoM365Usage'),
			            IF(
			                'SecDemoM365Usage'[Workload] = "MicrosoftTeams" &&
			                'SecDemoM365Usage'[Operation] = "MeetingParticipantJoined",
			                1,
			                0
			            )
			        ),
			    SelectedApp = "Teams" && SelectedActivity = "Scheduled Recurring Meetings Attended",
			        SUMX(
			            RELATEDTABLE('SecDemoM365Usage'),
			            IF(
			                'SecDemoM365Usage'[Workload] = "MicrosoftTeams" &&
			                'SecDemoM365Usage'[Operation] = "MeetingParticipantJoined",
			                1,
			                0
			            )
			        ),
			    SelectedApp = "Teams" && SelectedActivity = "Scheduled Recurring Meetings Organized",
			        SUMX(
			            RELATEDTABLE('SecDemoM365Usage'),
			            IF(
			                'SecDemoM365Usage'[Workload] = "MicrosoftTeams" &&
			                'SecDemoM365Usage'[Operation] = "MeetingParticipantJoined",
			                1,
			                0
			            )
			        ),
			    SelectedApp = "Teams" && SelectedActivity = "Team Chat Message",
			        SUMX(
			            RELATEDTABLE('SecDemoM365Usage'),
			            IF(
			                'SecDemoM365Usage'[Workload] = "MicrosoftTeams" &&
			                'SecDemoM365Usage'[Operation] IN {"MessageSent", "MessageRead"},
			                1,
			                0
			            )
			        ),
			    
			    // OUTLOOK ACTIVITIES
			    SelectedApp = "Outlook" && SelectedActivity = "Meeting Created",
			        SUMX(
			            RELATEDTABLE('SecDemoM365Usage'),
			            IF(
			                'SecDemoM365Usage'[Workload] = "Exchange" &&
			                'SecDemoM365Usage'[Operation] IN {"mailboxlogin", "mailitemsaccessed", "send"},
			                1,
			                0
			            )
			        ),
			    SelectedApp = "Outlook" && SelectedActivity = "Meeting Interacted",
			        SUMX(
			            RELATEDTABLE('SecDemoM365Usage'),
			            IF(
			                'SecDemoM365Usage'[Workload] = "Exchange" &&
			                'SecDemoM365Usage'[Operation] = "mailitemsaccessed",
			                1,
			                0
			            )
			        ),
			    SelectedApp = "Outlook" && SelectedActivity = "Read",
			        SUMX(
			            RELATEDTABLE('SecDemoM365Usage'),
			            IF(
			                'SecDemoM365Usage'[Workload] = "Exchange" &&
			                'SecDemoM365Usage'[Operation] = "mailitemsaccessed",
			                1,
			                0
			            )
			        ),
			    SelectedApp = "Outlook" && SelectedActivity = "Receive",
			        SUMX(
			            RELATEDTABLE('SecDemoM365Usage'),
			            IF(
			                'SecDemoM365Usage'[Workload] = "Exchange" &&
			                'SecDemoM365Usage'[Operation] = "mailitemsaccessed",
			                1,
			                0
			            )
			        ),
			    SelectedApp = "Outlook" && SelectedActivity = "Send",
			        SUMX(
			            RELATEDTABLE('SecDemoM365Usage'),
			            IF(
			                'SecDemoM365Usage'[Workload] = "Exchange" &&
			                'SecDemoM365Usage'[Operation] = "send",
			                1,
			                0
			            )
			        ),
			    
			    // WORD ACTIVITIES
			    SelectedApp = "Word" && SelectedActivity = "FileViewed",
			        SUMX(
			            RELATEDTABLE('SecDemoM365Usage'),
			            IF(
			                LOWER('SecDemoM365Usage'[SourceFileExtension]) IN { "docx", "doc", "dotx" } &&
			                'SecDemoM365Usage'[Operation] = "FileViewed",
			                1,
			                0
			            )
			        ),
			    SelectedApp = "Word" && SelectedActivity = "FileModified",
			        SUMX(
			            RELATEDTABLE('SecDemoM365Usage'),
			            IF(
			                LOWER('SecDemoM365Usage'[SourceFileExtension]) IN { "docx", "doc", "dotx" } &&
			                'SecDemoM365Usage'[Operation] = "FileModified",
			                1,
			                0
			            )
			        ),
			    SelectedApp = "Word" && SelectedActivity = "FileDownloaded",
			        SUMX(
			            RELATEDTABLE('SecDemoM365Usage'),
			            IF(
			                LOWER('SecDemoM365Usage'[SourceFileExtension]) IN { "docx", "doc", "dotx" } &&
			                'SecDemoM365Usage'[Operation] = "FileDownloaded",
			                1,
			                0
			            )
			        ),
			    SelectedApp = "Word" && SelectedActivity = "FileUploaded",
			        SUMX(
			            RELATEDTABLE('SecDemoM365Usage'),
			            IF(
			                LOWER('SecDemoM365Usage'[SourceFileExtension]) IN { "docx", "doc", "dotx" } &&
			                'SecDemoM365Usage'[Operation] = "FileUploaded",
			                1,
			                0
			            )
			        ),
			    
			    // EXCEL ACTIVITIES
			    SelectedApp = "Excel" && SelectedActivity = "FileViewed",
			        SUMX(
			            RELATEDTABLE('SecDemoM365Usage'),
			            IF(
			                LOWER('SecDemoM365Usage'[SourceFileExtension]) IN { "xlsx", "xls", "xlsm", "csv" } &&
			                'SecDemoM365Usage'[Operation] = "FileViewed",
			                1,
			                0
			            )
			        ),
			    SelectedApp = "Excel" && SelectedActivity = "FileModified",
			        SUMX(
			            RELATEDTABLE('SecDemoM365Usage'),
			            IF(
			                LOWER('SecDemoM365Usage'[SourceFileExtension]) IN { "xlsx", "xls", "xlsm", "csv" } &&
			                'SecDemoM365Usage'[Operation] = "FileModified",
			                1,
			                0
			            )
			        ),
			    SelectedApp = "Excel" && SelectedActivity = "FileDownloaded",
			        SUMX(
			            RELATEDTABLE('SecDemoM365Usage'),
			            IF(
			                LOWER('SecDemoM365Usage'[SourceFileExtension]) IN { "xlsx", "xls", "xlsm", "csv" } &&
			                'SecDemoM365Usage'[Operation] = "FileDownloaded",
			                1,
			                0
			            )
			        ),
			    SelectedApp = "Excel" && SelectedActivity = "FileUploaded",
			        SUMX(
			            RELATEDTABLE('SecDemoM365Usage'),
			            IF(
			                LOWER('SecDemoM365Usage'[SourceFileExtension]) IN { "xlsx", "xls", "xlsm", "csv" } &&
			                'SecDemoM365Usage'[Operation] = "FileUploaded",
			                1,
			                0
			            )
			        ),
			    
			    // POWERPOINT ACTIVITIES
			    SelectedApp = "PowerPoint" && SelectedActivity = "FileViewed",
			        SUMX(
			            RELATEDTABLE('SecDemoM365Usage'),
			            IF(
			                LOWER('SecDemoM365Usage'[SourceFileExtension]) IN { "pptx", "ppt", "ppsx" } &&
			                'SecDemoM365Usage'[Operation] = "FileViewed",
			                1,
			                0
			            )
			        ),
			    SelectedApp = "PowerPoint" && SelectedActivity = "FileModified",
			        SUMX(
			            RELATEDTABLE('SecDemoM365Usage'),
			            IF(
			                LOWER('SecDemoM365Usage'[SourceFileExtension]) IN { "pptx", "ppt", "ppsx" } &&
			                'SecDemoM365Usage'[Operation] = "FileModified",
			                1,
			                0
			            )
			        ),
			    SelectedApp = "PowerPoint" && SelectedActivity = "FileDownloaded",
			        SUMX(
			            RELATEDTABLE('SecDemoM365Usage'),
			            IF(
			                LOWER('SecDemoM365Usage'[SourceFileExtension]) IN { "pptx", "ppt", "ppsx" } &&
			                'SecDemoM365Usage'[Operation] = "FileDownloaded",
			                1,
			                0
			            )
			        ),
			    SelectedApp = "PowerPoint" && SelectedActivity = "FileUploaded",
			        SUMX(
			            RELATEDTABLE('SecDemoM365Usage'),
			            IF(
			                LOWER('SecDemoM365Usage'[SourceFileExtension]) IN { "pptx", "ppt", "ppsx" } &&
			                'SecDemoM365Usage'[Operation] = "FileUploaded",
			                1,
			                0
			            )
			        ),
			    
			    BLANK()
			)
			```
		formatString: 0
		lineageTag: be75419c-007e-4aca-b40c-2e9a7ec8b6a2

	column App
		lineageTag: b64dbc1d-2662-4fcf-a0d2-12655967dbd9
		summarizeBy: none
		isNameInferred
		sourceColumn: [App]

		annotation SummarizationSetBy = Automatic

	column Activity
		lineageTag: 2dddb59e-9c9e-4922-ada1-e6ea66a39c80
		summarizeBy: none
		isNameInferred
		sourceColumn: [Activity]

		annotation SummarizationSetBy = Automatic

	partition 'App Activity LL' = calculated
		mode: import
		source =
				
				DATATABLE(
				    "App", STRING,
				    "Activity", STRING,
				    {
				        {"Teams", "Ad Hoc Meetings Attended"},
				        {"Teams", "Ad Hoc Meetings Organized"},
				        {"Teams", "Call"},
				        {"Teams", "Meeting"},
				        {"Teams", "Meetings Attended"},
				        {"Teams", "Meetings Organized"},
				        {"Teams", "Private Chat Message"},
				        {"Teams", "Scheduled One-time Meetings Attended"},
				        {"Teams", "Scheduled One-time Meetings Organized"},
				        {"Teams", "Scheduled Recurring Meetings Attended"},
				        {"Teams", "Scheduled Recurring Meetings Organized"},
				        {"Teams", "Team Chat Message"},
				        {"Outlook", "Meeting Created"},
				        {"Outlook", "Meeting Interacted"},
				        {"Outlook", "Read"},
				        {"Outlook", "Receive"},
				        {"Outlook", "Send"},
				        {"Word", "FileViewed"},
				        {"Word", "FileModified"},
				        {"Word", "FileDownloaded"},
				        {"Word", "FileUploaded"},
				        {"Excel", "FileViewed"},
				        {"Excel", "FileModified"},
				        {"Excel", "FileDownloaded"},
				        {"Excel", "FileUploaded"},
				        {"PowerPoint", "FileViewed"},
				        {"PowerPoint", "FileModified"},
				        {"PowerPoint", "FileDownloaded"},
				        {"PowerPoint", "FileUploaded"}
				    }
				)

	annotation PBI_Id = 9d7bbea60f11472481df74dfe666634d

