table 'Copilot Qualification Criteria LL'
	lineageTag: 112ed30b-a881-4b92-bcbd-04e1a6351196

	measure '# of Users Qualifying LL V2' =
			
			VAR SelectedTier = SELECTEDVALUE('Copilot Qualification Criteria LL'[Tier])
			RETURN
			SWITCH(
			    SelectedTier,
			    1, COUNTROWS(FILTER(ALL('SecDemEntraUsers'), CALCULATE([M365 All Apps Tier V2]) = 1)),
			    2, COUNTROWS(FILTER(ALL('SecDemEntraUsers'), CALCULATE([M365 All Apps Tier V2]) = 2)),
			    3, COUNTROWS(FILTER(ALL('SecDemEntraUsers'), CALCULATE([M365 All Apps Tier V2]) = 3)),
			    4, COUNTROWS(FILTER(ALL('SecDemEntraUsers'), CALCULATE([M365 All Apps Tier V2]) = 4)),
			    BLANK()
			)
		formatString: 0
		lineageTag: cfe06efc-52b9-4111-a45d-83575c219aec

	measure 'Total Active Users LL' =
			
			CALCULATE(
			    DISTINCTCOUNT('SecDemEntraUsers'[userPrincipalName]),
			    FILTER(
			        'SecDemEntraUsers',
			        NOT(ISBLANK([M365 All Apps Tier V2]))
			    )
			)
		formatString: 0
		lineageTag: c0932df2-517c-47c5-8763-b659507ce168

	measure '# of Users Qualifying Weighted V2' =
			
			CALCULATE(
			    DISTINCTCOUNT('SecDemoM365Usage'[UserId]),
			    FILTER(
			        ALL('SecDemoM365Usage'[UserId]),
			        [M365 All Apps Tier Weighted V2] = SELECTEDVALUE('Copilot Qualification Criteria LL'[Tier])
			    )
			)
		formatString: 0
		lineageTag: 5a2a337f-7654-4c98-878d-2c640331200c

	column Tier
		formatString: 0
		lineageTag: f4a80e84-d907-476b-bf6b-27e1ddbf05f1
		summarizeBy: sum
		isNameInferred
		sourceColumn: [Tier]

		annotation SummarizationSetBy = Automatic

	column Description
		lineageTag: 360b1477-c3aa-4870-9483-6b857c8f599e
		summarizeBy: none
		isNameInferred
		sourceColumn: [Description]

		annotation SummarizationSetBy = Automatic

	column 'Overall M365 Activity LL'
		lineageTag: c32cb492-3898-481a-b343-6e413451ad59
		summarizeBy: none
		isNameInferred
		sourceColumn: [Overall M365 Activity LL]

		annotation SummarizationSetBy = Automatic

	partition 'Copilot Qualification Criteria LL' = calculated
		mode: import
		source =
				
				DATATABLE(
				    "Tier", INTEGER,
				    "Overall M365 Activity LL", STRING,
				    "Description", STRING,
				    {
				        {1, "Top 10%", "Core high-value group"},
				        {2, "Top 10-25%", "Well-rounded power users"},
				        {3, "Top 25-50%", "Regular active users with growth potential"},
				        {4, "Remaining 50%", "Broad inclusion (if budget allows)"}
				    }
				)

	annotation PBI_Id = 6d7b68c126dc48ea9e58a24aad3d0e0c

