table 'Copilot Measures'
	lineageTag: 8ba4870e-0e78-4ee3-9437-0f9882cd113f

	measure 'Copilot Teams Interactions' =
			
			CALCULATE(
			    COUNTROWS('SecDemoM365Usage'),
			    'SecDemoM365Usage'[Operation] = "CopilotInteraction",
			    'SecDemoM365Usage'[AppHost] = "Teams"
			)
		formatString: 0
		lineageTag: 31de532b-df26-4b8f-b9ac-2f23e21ff017

	measure 'Copilot Outlook Interactions' =
			
			CALCULATE(
			    COUNTROWS('SecDemoM365Usage'),
			    'SecDemoM365Usage'[Operation] = "CopilotInteraction",
			    'SecDemoM365Usage'[AppHost] = "Outlook"
			)
		formatString: 0
		lineageTag: 11e84140-d9a3-46d6-9b1d-8189e91f7679

	measure 'Copilot Word Interactions' =
			
			CALCULATE(
			    COUNTROWS('SecDemoM365Usage'),
			    'SecDemoM365Usage'[Operation] = "CopilotInteraction",
			    'SecDemoM365Usage'[AppHost] = "Word"
			)
		formatString: 0
		lineageTag: 51395c29-63d4-4801-842d-30b8a2d695ce

	measure 'Copilot Excel Interactions' =
			
			CALCULATE(
			    COUNTROWS('SecDemoM365Usage'),
			    'SecDemoM365Usage'[Operation] = "CopilotInteraction",
			    'SecDemoM365Usage'[AppHost] = "Excel"
			)
		formatString: 0
		lineageTag: 67843e5b-7497-4bed-b1e7-8ed4e3cc4746

	measure 'Copilot PowerPoint Interactions' =
			
			CALCULATE(
			    COUNTROWS('SecDemoM365Usage'),
			    'SecDemoM365Usage'[Operation] = "CopilotInteraction",
			    'SecDemoM365Usage'[AppHost] = "PowerPoint"
			)
		formatString: 0
		lineageTag: 64b0aa9b-998f-448e-bf99-b4749761d754

	measure 'Copilot All Apps Total' =
			
			CALCULATE(
			    COUNTROWS('SecDemoM365Usage'),
			    'SecDemoM365Usage'[Operation] = "CopilotInteraction"
			)
		formatString: 0
		lineageTag: 57fcc378-912a-45bb-a55a-0629a20a9c2a

	measure 'Copilot All Apps Tier' = ```
			
			VAR UserCopilotScore = [Copilot All Apps Total]
			VAR P90 = CALCULATE(
			    PERCENTILEX.INC(
			        ALL('SecDemoM365Usage'[UserId]), 
			        [Copilot All Apps Total], 
			        0.90
			    ), 
			    ALLSELECTED()
			)
			VAR P75 = CALCULATE(
			    PERCENTILEX.INC(
			        ALL('SecDemoM365Usage'[UserId]), 
			        [Copilot All Apps Total], 
			        0.75
			    ), 
			    ALLSELECTED()
			)
			VAR P50 = CALCULATE(
			    PERCENTILEX.INC(
			        ALL('SecDemoM365Usage'[UserId]), 
			        [Copilot All Apps Total], 
			        0.50
			    ), 
			    ALLSELECTED()
			)
			RETURN 
			SWITCH(
			    TRUE(),
			    ISBLANK(UserCopilotScore), BLANK(),
			    UserCopilotScore >= P90, 1,
			    UserCopilotScore >= P75, 2,
			    UserCopilotScore >= P50, 3,
			    4
			)
			```
		formatString: 0
		lineageTag: 36cc2f83-3b7b-4ce7-a098-db1e6fdbde49

	measure 'Copilot Usage Activity' =
			
			SWITCH(
			    [Copilot All Apps Tier],
			    1, "Top 10%",
			    2, "10-25%",
			    3, "25-50%",
			    4, "Bottom 50%",
			    BLANK()
			)
		lineageTag: bae30ea0-ccf7-4dfe-9242-9a6499b13772

	measure '# of Copilot Users' =
			
			CALCULATE(
			    DISTINCTCOUNT('SecDemEntraUsers'[userPrincipalName]),
			    'SecDemoM365Usage'[Operation] = "CopilotInteraction"
			)
		formatString: 0
		lineageTag: c57f49db-3293-46a3-a58e-5118d19d41b4

	measure 'Selected App Copilot Interactions' =
			
			VAR SelectedApp = SELECTEDVALUE('App Selection'[AppName])
			RETURN
			SWITCH(
			    SelectedApp,
			    "M365 All Apps", [Copilot All Apps Total],
			    "Teams", [Copilot Teams Interactions],
			    "Outlook", [Copilot Outlook Interactions],
			    "Word", [Copilot Word Interactions],
			    "Excel", [Copilot Excel Interactions],
			    "PowerPoint", [Copilot PowerPoint Interactions],
			    BLANK()
			)
		formatString: 0
		lineageTag: e1b2b05f-4a22-496b-a491-1e3ce2142e5a

	measure 'Selected App Copilot Tier Label' = ```
			
			VAR SelectedApp = 
			    IF(
			        HASONEVALUE('SecDemoM365Usage'[App Column]),
			        VALUES('SecDemoM365Usage'[App Column]),
			        "M365 All Apps"
			    )
			VAR UserCopilotScore = [Selected App Copilot Interactions]
			VAR P90 = CALCULATE(
			    PERCENTILEX.INC(
			        ADDCOLUMNS(
			            VALUES('SecDemoM365Usage'[UserId]),
			            "UserScore", [Selected App Copilot Interactions]
			        ),
			        [UserScore],
			        0.90
			    ),
			    REMOVEFILTERS('SecDemoM365Usage')
			)
			VAR P75 = CALCULATE(
			    PERCENTILEX.INC(
			        ADDCOLUMNS(
			            VALUES('SecDemoM365Usage'[UserId]),
			            "UserScore", [Selected App Copilot Interactions]
			        ),
			        [UserScore],
			        0.75
			    ),
			    REMOVEFILTERS('SecDemoM365Usage')
			)
			VAR P50 = CALCULATE(
			    PERCENTILEX.INC(
			        ADDCOLUMNS(
			            VALUES('SecDemoM365Usage'[UserId]),
			            "UserScore", [Selected App Copilot Interactions]
			        ),
			        [UserScore],
			        0.50
			    ),
			    REMOVEFILTERS('SecDemoM365Usage')
			)
			VAR TierValue = SWITCH(
			    TRUE(),
			    ISBLANK(UserCopilotScore), BLANK(),
			    UserCopilotScore >= P90, 1,
			    UserCopilotScore >= P75, 2,
			    UserCopilotScore >= P50, 3,
			    4
			)
			RETURN 
			SWITCH(
			    TierValue,
			    1, "Top 10%",
			    2, "10-25%",
			    3, "25-50%",
			    4, "Bottom 50%",
			    BLANK()
			)
			```
		lineageTag: 75178224-1a6b-4e38-a07b-8bfd4521b358

	measure 'Copilot Usage Rank' = ```
			
			VAR RankValue = 
			    RANKX(
			        ALLSELECTED('SecDemoM365Usage'[UserId]),
			        [Selected App Copilot Interactions]
			    )
			VAR TotalUsers = COUNTROWS(ALLSELECTED('SecDemoM365Usage'[UserId]))
			RETURN DIVIDE(RankValue, TotalUsers, 0)
			```
		lineageTag: c3702d41-9f8d-4062-a46e-80c914b02203

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Priority Text Only' = ```
			
			VAR PriorityWithEmoji = [Selected App Priority]
			RETURN 
			    SWITCH(
			        TRUE(),
			        CONTAINSSTRING(PriorityWithEmoji, "Critical"), "Critical",
			        CONTAINSSTRING(PriorityWithEmoji, "Promoter"), "Promoter",
			        CONTAINSSTRING(PriorityWithEmoji, "High"), "High",
			        CONTAINSSTRING(PriorityWithEmoji, "Medium"), "Medium",
			        CONTAINSSTRING(PriorityWithEmoji, "Low"), "Low",
			        BLANK()
			    )
			```
		lineageTag: 664e4908-b699-4a1b-945f-4b4dc4c658fe

	measure 'Priority For Chart' =
			
			IF(
			    ISBLANK([Selected App Priority]),
			    BLANK(),
			    SWITCH(
			        TRUE(),
			        CONTAINSSTRING([Selected App Priority], "Critical"), "Critical",
			        CONTAINSSTRING([Selected App Priority], "Promoter"), "Promoter",
			        CONTAINSSTRING([Selected App Priority], "High"), "High",
			        CONTAINSSTRING([Selected App Priority], "Medium"), "Medium",
			        "Low"
			    )
			)
		lineageTag: c3d474c0-34ad-4d24-8ec0-0cb7f3f6adfb

	measure 'User Count - Copilot' =
			
			CALCULATE(
			    DISTINCTCOUNT('SecDemoM365Usage'[UserId]),
			    'SecDemoM365Usage'[Is Copilot User] = "Copilot User"
			)
		formatString: 0
		lineageTag: 82e3e882-8fb7-4570-a714-0d2ee93ed51f

	measure 'User Count - Non-Copilot' =
			
			CALCULATE(
			    DISTINCTCOUNT('SecDemoM365Usage'[UserId]),
			    'SecDemoM365Usage'[Is Copilot User] = "Non-Copilot User"
			)
		formatString: 0
		lineageTag: 59f79103-9637-47db-a546-9dbf9230b06c

	measure 'Users by M365 Tier' =
			
			VAR CurrentTier = SELECTEDVALUE('M365 Tiers'[M365TierName])
			RETURN
			COUNTROWS(
			    FILTER(
			        SecDemEntraUsers,
			        [Selected App M365 Tier Label] = CurrentTier
			    )
			)
		formatString: 0
		lineageTag: 50e37cd7-c920-4b54-bda2-cec8f432ac37

	measure 'CE Quadrant' =
			VAR M365Tier = [Selected App M365 Tier Label]
			VAR CopilotTier = [Selected App Copilot Tier Label]
			VAR IsHighM365 = M365Tier IN {"Top 10%", "10-25%"}
			VAR IsHighCopilot = CopilotTier IN {"Top 10%", "10-25%"}
			RETURN
			    SWITCH(TRUE(),
			        ISBLANK(M365Tier), BLANK(),
			        IsHighM365 && NOT IsHighCopilot, "Enablement Targets",
			        IsHighM365 && IsHighCopilot, "Champions",
			        NOT IsHighM365 && IsHighCopilot, "AI-First",
			        "Low Engagement"
			    )
		lineageTag: a1b2c3d4-e5f6-7890-abcd-ef1234567890

	measure 'CE Enablement Targets Count' = COUNTROWS(FILTER(ALLSELECTED(SecDemEntraUsers), [CE Quadrant] = "Enablement Targets"))
		formatString: 0
		lineageTag: b2c3d4e5-f6a7-8901-bcde-f12345678901

	measure 'CE Champions Count' = COUNTROWS(FILTER(ALLSELECTED(SecDemEntraUsers), [CE Quadrant] = "Champions"))
		formatString: 0
		lineageTag: c3d4e5f6-a7b8-9012-cdef-123456789012

	measure 'CE AI-First Count' = COUNTROWS(FILTER(ALLSELECTED(SecDemEntraUsers), [CE Quadrant] = "AI-First"))
		formatString: 0
		lineageTag: d4e5f6a7-b8c9-0123-defa-234567890123

	measure 'CE Low Engagement Count' = COUNTROWS(FILTER(ALLSELECTED(SecDemEntraUsers), [CE Quadrant] = "Low Engagement"))
		formatString: 0
		lineageTag: e5f6a7b8-c9d0-1234-efab-345678901234

	measure 'CE App Percentile' =
			VAR UserScore = [Selected App M365 Activity]
			VAR AllScores =
			    ADDCOLUMNS(
			        ALL(SecDemEntraUsers[userPrincipalName]),
			        "@s", [Selected App M365 Activity]
			    )
			VAR ActiveScores = FILTER(AllScores, NOT(ISBLANK([@s])))
			VAR Below = COUNTROWS(FILTER(ActiveScores, [@s] <= UserScore))
			VAR Total = COUNTROWS(ActiveScores)
			RETURN IF(NOT(ISBLANK(UserScore)) && Total > 0, ROUND(DIVIDE(Below, Total) * 100, 0), BLANK())
		formatString: 0
		lineageTag: f6a7b8c9-d0e1-2345-fabc-456789012345

	measure 'CE Copilot Percentile' =
			VAR UserScore = [Selected App Copilot Interactions]
			VAR AllScores =
			    ADDCOLUMNS(
			        ALL(SecDemEntraUsers[userPrincipalName]),
			        "@s", [Selected App Copilot Interactions]
			    )
			VAR ActiveScores = FILTER(AllScores, NOT(ISBLANK([@s])))
			VAR Below = COUNTROWS(FILTER(ActiveScores, [@s] <= UserScore))
			VAR Total = COUNTROWS(ActiveScores)
			RETURN IF(NOT(ISBLANK(UserScore)) && Total > 0, ROUND(DIVIDE(Below, Total) * 100, 0), BLANK())
		formatString: 0
		lineageTag: a7b8c9d0-e1f2-3456-abcd-567890123456

	measure 'CE Is Selected Quadrant' =
			VAR SelectedQ = SELECTEDVALUE('CE Quadrant Selection'[QuadrantName], "Enablement Targets")
			RETURN IF([CE Quadrant] = SelectedQ, 1, BLANK())
		formatString: 0
		lineageTag: 11223344-5566-7788-99aa-bbccddeeff00

	measure 'CE Selected Quadrant Count' =
			VAR SelectedQ = SELECTEDVALUE('CE Quadrant Selection'[QuadrantName], "Enablement Targets")
			RETURN
			    SWITCH(SelectedQ,
			        "Enablement Targets", [CE Enablement Targets Count],
			        "Champions", [CE Champions Count],
			        "AI-First", [CE AI-First Count],
			        "Low Engagement", [CE Low Engagement Count],
			        BLANK()
			    )
		formatString: 0
		lineageTag: 22334455-6677-8899-aabb-ccddeeff0011

	column Column
		formatString: 0
		lineageTag: 80f4da38-73aa-4315-99e2-04c533165fd5
		summarizeBy: sum
		isNameInferred
		sourceColumn: [Column]

		annotation SummarizationSetBy = Automatic

	partition 'Copilot Measures' = calculated
		mode: import
		source = Row("Column", BLANK())

	annotation PBI_Id = 1752aa60ea98432aa7d4f954393b9e57

	annotation 436ba87b-9c83-4389-a31b-ebd06a36be98 = {"Expression":""}

