/// Host table for Licensing Page measures
table 'LP Measures'
	isHidden
	lineageTag: 1a52bc3d-8e82-4edf-b8a0-539bedf8b2f3

	/// Teams weight resolved from selected profile or manual slicer
	measure 'LP Teams Weight' =
			VAR Profile = SELECTEDVALUE('LP Weight Profiles'[ProfileName])
			RETURN
			    SWITCH(
			        Profile,
			        "Balanced", 0.17,
			        "Collaboration Focus", 0.30,
			        "Content Creation Focus", 0.10,
			        SELECTEDVALUE('Teams Weight %'[Teams Weight], 17) / 100
			    )
		formatString: 0%
		displayFolder: Weights
		lineageTag: 25ccb563-61df-471c-b02f-33c716927800

	/// Outlook weight resolved from selected profile or manual slicer
	measure 'LP Outlook Weight' =
			VAR Profile = SELECTEDVALUE('LP Weight Profiles'[ProfileName])
			RETURN
			    SWITCH(
			        Profile,
			        "Balanced", 0.17,
			        "Collaboration Focus", 0.30,
			        "Content Creation Focus", 0.10,
			        SELECTEDVALUE('Outlook Weight %'[Outlook Weight %], 17) / 100
			    )
		formatString: 0%
		displayFolder: Weights
		lineageTag: e538ffec-de45-4fc8-9ce4-a18095ad5a63

	/// Word weight resolved from selected profile or manual slicer
	measure 'LP Word Weight' =
			VAR Profile = SELECTEDVALUE('LP Weight Profiles'[ProfileName])
			RETURN
			    SWITCH(
			        Profile,
			        "Balanced", 0.17,
			        "Collaboration Focus", 0.08,
			        "Content Creation Focus", 0.20,
			        SELECTEDVALUE('Word Weight %'[Word Weight %], 17) / 100
			    )
		formatString: 0%
		displayFolder: Weights
		lineageTag: db0547c3-8eb2-4271-89a6-e9492f0010a1

	/// Excel weight resolved from selected profile or manual slicer
	measure 'LP Excel Weight' =
			VAR Profile = SELECTEDVALUE('LP Weight Profiles'[ProfileName])
			RETURN
			    SWITCH(
			        Profile,
			        "Balanced", 0.17,
			        "Collaboration Focus", 0.08,
			        "Content Creation Focus", 0.20,
			        SELECTEDVALUE('Excel Weight %'[Excel Weight %], 17) / 100
			    )
		formatString: 0%
		displayFolder: Weights
		lineageTag: bb5ca14f-742b-4ccd-ad3e-3b25059eaba2

	/// PowerPoint weight resolved from selected profile or manual slicer
	measure 'LP PowerPoint Weight' =
			VAR Profile = SELECTEDVALUE('LP Weight Profiles'[ProfileName])
			RETURN
			    SWITCH(
			        Profile,
			        "Balanced", 0.16,
			        "Collaboration Focus", 0.08,
			        "Content Creation Focus", 0.20,
			        SELECTEDVALUE('PowerPoint Weight %'[PowerPoint Weight %], 16) / 100
			    )
		formatString: 0%
		displayFolder: Weights
		lineageTag: 08be6e5e-894e-4467-8c71-917bef9d0770

	/// Teams raw activity * LP weight
	measure 'LP Teams Weighted' =
			VAR Raw =
			    SUMX(
			        RELATEDTABLE('SecDemoM365Usage'),
			        IF(
			            'SecDemoM365Usage'[Workload] = "MicrosoftTeams" &&
			            'SecDemoM365Usage'[Operation] IN {"MessageSent", "MessageRead", "MeetingParticipantJoined"},
			            1, 0
			        )
			    )
			RETURN Raw * [LP Teams Weight]
		isHidden
		displayFolder: App Scores
		lineageTag: 92cbfcba-142c-408f-9323-4c850852d5f0

	/// Outlook raw activity * LP weight
	measure 'LP Outlook Weighted' =
			VAR Raw =
			    SUMX(
			        RELATEDTABLE('SecDemoM365Usage'),
			        IF(
			            'SecDemoM365Usage'[Workload] = "Exchange" &&
			            'SecDemoM365Usage'[Operation] IN {"Send", "MailItemsAccessed"},
			            1, 0
			        )
			    )
			RETURN Raw * [LP Outlook Weight]
		isHidden
		displayFolder: App Scores
		lineageTag: 07edb68f-7bce-4042-95a2-d49b62aac3f9

	/// Word raw activity * LP weight
	measure 'LP Word Weighted' =
			VAR Raw =
			    SUMX(
			        RELATEDTABLE('SecDemoM365Usage'),
			        IF(
			            LOWER('SecDemoM365Usage'[SourceFileExtension]) IN {"docx", "doc", "dotx"} &&
			            'SecDemoM365Usage'[Operation] IN {"FileViewed", "FileModified", "FileDownloaded", "FileUploaded"},
			            1, 0
			        )
			    )
			RETURN Raw * [LP Word Weight]
		isHidden
		displayFolder: App Scores
		lineageTag: 72b66c37-b09e-46ca-8793-3de9f436ced1

	/// Excel raw activity * LP weight
	measure 'LP Excel Weighted' =
			VAR Raw =
			    SUMX(
			        RELATEDTABLE('SecDemoM365Usage'),
			        IF(
			            LOWER('SecDemoM365Usage'[SourceFileExtension]) IN {"xlsx", "xls", "xlsm", "csv"} &&
			            'SecDemoM365Usage'[Operation] IN {"FileViewed", "FileModified", "FileDownloaded", "FileUploaded"},
			            1, 0
			        )
			    )
			RETURN Raw * [LP Excel Weight]
		isHidden
		displayFolder: App Scores
		lineageTag: 0b3aa351-620e-49e6-b258-cc25d1af8f39

	/// PowerPoint raw activity * LP weight
	measure 'LP PowerPoint Weighted' =
			VAR Raw =
			    SUMX(
			        RELATEDTABLE('SecDemoM365Usage'),
			        IF(
			            LOWER('SecDemoM365Usage'[SourceFileExtension]) IN {"pptx", "ppt", "ppsx"} &&
			            'SecDemoM365Usage'[Operation] IN {"FileViewed", "FileModified", "FileDownloaded", "FileUploaded"},
			            1, 0
			        )
			    )
			RETURN Raw * [LP PowerPoint Weight]
		isHidden
		displayFolder: App Scores
		lineageTag: 43ad7b37-6d74-4219-bf5f-8295d0b2fc0a

	/// Sum of all LP weighted app activities
	measure 'LP Weighted Total' = [LP Teams Weighted] + [LP Outlook Weighted] + [LP Word Weighted] + [LP Excel Weighted] + [LP PowerPoint Weighted] + [LP Copilot Chat Weighted]
		isHidden
		displayFolder: App Scores
		lineageTag: 42f1303d-c755-4ad3-b8d8-68f04818876c

	/// Percentile-based score (0-100) using RANKX Skip for full 0-100 range. Higher = more active M365 user.
	measure 'LP Composite Score' =
			VAR UserTotal = [LP Weighted Total]
			VAR AllUsers =
			    FILTER(
			        ALLSELECTED(SecDemEntraUsers),
			        [LP Weighted Total] > 0
			    )
			VAR TotalCount = COUNTROWS(AllUsers)
			VAR UserRank =
			    RANKX(
			        AllUsers,
			        [LP Weighted Total],
			        ,
			        ASC,
			        Skip
			    )
			RETURN
			    IF(
			        NOT(ISBLANK(UserTotal)) && UserTotal > 0 && TotalCount > 0,
			        ROUND(UserRank / TotalCount * 100, 0),
			        BLANK()
			    )
		formatString: 0
		displayFolder: Scoring
		lineageTag: ff1f6359-1497-4e28-81e6-9c6efe0cf050

	/// Dense rank among filtered users by composite score (1 = highest)
	measure 'LP Candidate Rank' =
			IF(
			    NOT(ISBLANK([LP Composite Score])),
			    RANKX(
			        ALLSELECTED(SecDemEntraUsers),
			        [LP Composite Score],
			        ,
			        DESC,
			        Dense
			    ),
			    BLANK()
			)
		formatString: 0
		displayFolder: Scoring
		lineageTag: dfc52857-5af3-43e4-ab02-a56a20ff22b7

	/// Licensing action based on PERCENTILEX.INC thresholds on weighted total. Labels: License First / License Next / Potential / Developing.
	measure 'LP Action' =
			VAR UserTotal = [LP Weighted Total]
			VAR AllUsers =
			    FILTER(
			        ALLSELECTED(SecDemEntraUsers),
			        [LP Weighted Total] > 0
			    )
			VAR P90 = PERCENTILEX.INC(AllUsers, [LP Weighted Total], 0.90)
			VAR P75 = PERCENTILEX.INC(AllUsers, [LP Weighted Total], 0.75)
			VAR P50 = PERCENTILEX.INC(AllUsers, [LP Weighted Total], 0.50)
			RETURN
			    SWITCH(
			        TRUE(),
			        ISBLANK(UserTotal) || UserTotal <= 0, BLANK(),
			        UserTotal >= P90, "License First",
			        UserTotal >= P75, "License Next",
			        UserTotal >= P50, "Potential",
			        "Developing"
			    )
		displayFolder: Scoring
		lineageTag: 21d04867-5228-476d-b1f7-4daeb408f91f

	/// Teams contribution as % of total weighted score
	/// Percentile rank for Teams activity among active users (0–1, RANKX-based)
	measure 'LP Teams Pct' =
			VAR ActiveUsers = FILTER(ALLSELECTED(SecDemEntraUsers), [LP Weighted Total] > 0)
			VAR Total = COUNTROWS(ActiveUsers)
			VAR Rnk = RANKX(ActiveUsers, [LP Teams Weighted], , ASC, Skip)
			RETURN IF(Total > 0 && [LP Weighted Total] > 0, DIVIDE(Rnk, Total), BLANK())
		formatString: 0%
		displayFolder: App Breakdown
		lineageTag: be449560-df78-40fa-905b-199982794f94

	/// Percentile rank for Outlook activity among active users (0–1, RANKX-based)
	measure 'LP Outlook Pct' =
			VAR ActiveUsers = FILTER(ALLSELECTED(SecDemEntraUsers), [LP Weighted Total] > 0)
			VAR Total = COUNTROWS(ActiveUsers)
			VAR Rnk = RANKX(ActiveUsers, [LP Outlook Weighted], , ASC, Skip)
			RETURN IF(Total > 0 && [LP Weighted Total] > 0, DIVIDE(Rnk, Total), BLANK())
		formatString: 0%
		displayFolder: App Breakdown
		lineageTag: 971fdc6b-ba72-4102-84a2-9abd58c87196

	/// Percentile rank for Word activity among active users (0–1, RANKX-based)
	measure 'LP Word Pct' =
			VAR ActiveUsers = FILTER(ALLSELECTED(SecDemEntraUsers), [LP Weighted Total] > 0)
			VAR Total = COUNTROWS(ActiveUsers)
			VAR Rnk = RANKX(ActiveUsers, [LP Word Weighted], , ASC, Skip)
			RETURN IF(Total > 0 && [LP Weighted Total] > 0, DIVIDE(Rnk, Total), BLANK())
		formatString: 0%
		displayFolder: App Breakdown
		lineageTag: d1661beb-da8c-4f4e-85a3-f2837f7be797

	/// Percentile rank for Excel activity among active users (0–1, RANKX-based)
	measure 'LP Excel Pct' =
			VAR ActiveUsers = FILTER(ALLSELECTED(SecDemEntraUsers), [LP Weighted Total] > 0)
			VAR Total = COUNTROWS(ActiveUsers)
			VAR Rnk = RANKX(ActiveUsers, [LP Excel Weighted], , ASC, Skip)
			RETURN IF(Total > 0 && [LP Weighted Total] > 0, DIVIDE(Rnk, Total), BLANK())
		formatString: 0%
		displayFolder: App Breakdown
		lineageTag: fbc7c811-9673-4a2f-aa08-3ccb34f56088

	/// Percentile rank for PowerPoint activity among active users (0–1, RANKX-based)
	measure 'LP PowerPoint Pct' =
			VAR ActiveUsers = FILTER(ALLSELECTED(SecDemEntraUsers), [LP Weighted Total] > 0)
			VAR Total = COUNTROWS(ActiveUsers)
			VAR Rnk = RANKX(ActiveUsers, [LP PowerPoint Weighted], , ASC, Skip)
			RETURN IF(Total > 0 && [LP Weighted Total] > 0, DIVIDE(Rnk, Total), BLANK())
		formatString: 0%
		displayFolder: App Breakdown
		lineageTag: 10ace5ae-a55a-416f-9143-93f85771f495

	/// Text explanation of why this user is recommended, using new action labels
	measure 'LP Recommendation' =
			VAR TeamsW = [LP Teams Weighted]
			VAR OutlookW = [LP Outlook Weighted]
			VAR WordW = [LP Word Weighted]
			VAR ExcelW = [LP Excel Weighted]
			VAR PPTW = [LP PowerPoint Weighted]
			VAR CopilotW = [LP Copilot Chat Weighted]
			VAR Total = [LP Weighted Total]
			VAR Score = [LP Composite Score]
			VAR App1 =
			    SWITCH(
			        TRUE(),
			        TeamsW >= OutlookW && TeamsW >= WordW && TeamsW >= ExcelW && TeamsW >= PPTW && TeamsW >= CopilotW, "Teams",
			        OutlookW >= WordW && OutlookW >= ExcelW && OutlookW >= PPTW && OutlookW >= CopilotW, "Outlook",
			        WordW >= ExcelW && WordW >= PPTW && WordW >= CopilotW, "Word",
			        ExcelW >= PPTW && ExcelW >= CopilotW, "Excel",
			        PPTW >= CopilotW, "PowerPoint",
			        "Copilot Chat"
			    )
			VAR App2 =
			    SWITCH(
			        TRUE(),
			        App1 <> "Teams" && TeamsW >= IF(App1 = "Outlook", 0, OutlookW) && TeamsW >= IF(App1 = "Word", 0, WordW) && TeamsW >= IF(App1 = "Excel", 0, ExcelW) && TeamsW >= IF(App1 = "PowerPoint", 0, PPTW) && TeamsW >= IF(App1 = "Copilot Chat", 0, CopilotW), "Teams",
			        App1 <> "Outlook" && OutlookW >= IF(App1 = "Word", 0, WordW) && OutlookW >= IF(App1 = "Excel", 0, ExcelW) && OutlookW >= IF(App1 = "PowerPoint", 0, PPTW) && OutlookW >= IF(App1 = "Copilot Chat", 0, CopilotW), "Outlook",
			        App1 <> "Word" && WordW >= IF(App1 = "Excel", 0, ExcelW) && WordW >= IF(App1 = "PowerPoint", 0, PPTW) && WordW >= IF(App1 = "Copilot Chat", 0, CopilotW), "Word",
			        App1 <> "Excel" && ExcelW >= IF(App1 = "PowerPoint", 0, PPTW) && ExcelW >= IF(App1 = "Copilot Chat", 0, CopilotW), "Excel",
			        App1 <> "PowerPoint" && PPTW >= IF(App1 = "Copilot Chat", 0, CopilotW), "PowerPoint",
			        "Copilot Chat"
			    )
			VAR ActionLabel = [LP Action]
			RETURN
			    IF(
			        ISBLANK(Total) || Total = 0,
			        BLANK(),
			        ActionLabel & " — strongest in " & App1 & " & " & App2 & " (score " & Score & "/100)"
			    )
		displayFolder: Scoring
		lineageTag: 429fdbce-b16c-452f-b63f-c9e243f5eab0

	/// Count of users with M365 activity in current filter context
	measure 'LP Total Candidates' =
			COUNTROWS(
			    FILTER(
			        ALLSELECTED(SecDemEntraUsers),
			        NOT(ISBLANK([LP Composite Score]))
			    )
			)
		formatString: 0
		displayFolder: KPIs
		lineageTag: 693b6ed4-0898-4818-aa4d-fa4f40e64fc2

	/// Count of users in License First or License Next buckets
	measure 'LP Priority Candidates' =
			COUNTROWS(
			    FILTER(
			        ALLSELECTED(SecDemEntraUsers),
			        [LP Action] IN {"License First", "License Next"}
			    )
			)
		formatString: 0
		displayFolder: KPIs
		lineageTag: 7d93e358-83ec-438b-9dc7-f59299a6cf11

	/// Average composite score across filtered candidates
	measure 'LP Avg Score' =
			AVERAGEX(
			    FILTER(
			        ALLSELECTED(SecDemEntraUsers),
			        NOT(ISBLANK([LP Composite Score]))
			    ),
			    [LP Composite Score]
			)
		formatString: 0
		displayFolder: KPIs
		lineageTag: 73e44cb6-9197-4a5b-9f78-ed02679e614e

	/// Count of users per action category - works with any action slicer
	measure 'LP Action Users' =
			VAR CurrentAction = SELECTEDVALUE('Action Filter'[ActionName])
			VAR ActionMap =
			    SWITCH(
			        CurrentAction,
			        "Prioritize", "License First",
			        "License Next", "License Next",
			        "Enablement", "Potential",
			        "Monitor", "Developing",
			        CurrentAction
			    )
			RETURN
			    COUNTROWS(
			        FILTER(
			            ALLSELECTED(SecDemEntraUsers),
			            [LP Action] = ActionMap
			        )
			    )
		formatString: 0
		displayFolder: KPIs
		lineageTag: d838d0cc-f8bf-4331-b48c-dbf4c0e366b5

	/// Text showing current weight distribution + validation for Custom profile
	measure 'LP Weight Summary' =
			VAR T = FORMAT([LP Teams Weight], "0%")
			VAR O = FORMAT([LP Outlook Weight], "0%")
			VAR W = FORMAT([LP Word Weight], "0%")
			VAR E = FORMAT([LP Excel Weight], "0%")
			VAR P = FORMAT([LP PowerPoint Weight], "0%")
			VAR C = FORMAT([LP Copilot Chat Weight], "0%")
			VAR Profile = SELECTEDVALUE('LP Weight Profiles'[ProfileName])
			VAR IsCustom = Profile = "Custom" || ISBLANK(Profile)
			VAR Total = [LP Custom Weight Sum]
			VAR Validation = IF(NOT(IsCustom), "", IF(Total = 100, "  ✓", "  ⚠ Total: " & FORMAT(Total, "0") & "%"))
			RETURN
			"Teams " & T & "  ·  Outlook " & O & "  ·  Word " & W & "  ·  Excel " & E & "  ·  PPT " & P & "  ·  Copilot " & C & Validation
		displayFolder: Weights
		lineageTag: b4e5dc9c-c5a8-4cb9-bac0-9be02a4884f8

	/// Name of the user's strongest app by weighted activity
	measure 'LP Strongest App' =
			VAR TeamsW = [LP Teams Weighted]
			VAR OutlookW = [LP Outlook Weighted]
			VAR WordW = [LP Word Weighted]
			VAR ExcelW = [LP Excel Weighted]
			VAR PPTW = [LP PowerPoint Weighted]
			VAR CopilotW = [LP Copilot Chat Weighted]
			RETURN
			    SWITCH(
			        TRUE(),
			        ISBLANK([LP Weighted Total]) || [LP Weighted Total] = 0, BLANK(),
			        TeamsW >= OutlookW && TeamsW >= WordW && TeamsW >= ExcelW && TeamsW >= PPTW && TeamsW >= CopilotW, "Teams",
			        OutlookW >= WordW && OutlookW >= ExcelW && OutlookW >= PPTW && OutlookW >= CopilotW, "Outlook",
			        WordW >= ExcelW && WordW >= PPTW && WordW >= CopilotW, "Word",
			        ExcelW >= PPTW && ExcelW >= CopilotW, "Excel",
			        PPTW >= CopilotW, "PowerPoint",
			        "Copilot Chat"
			    )
		displayFolder: Scoring
		lineageTag: 9f8de4fa-fde2-48c5-a07a-d90aff285d0c

	/// Inline SVG stacked bar showing Teams/Outlook/Word/Excel/PowerPoint proportions per user. Colors: Teams=#6264A7, Outlook=#0078D4, Word=#2B579A, Excel=#217346, PPT=#D24726
	measure 'LP App Breakdown SVG' =
			VAR _Tp = IF(ISBLANK([LP Teams Pct]), 0, [LP Teams Pct])
			VAR _Op = IF(ISBLANK([LP Outlook Pct]), 0, [LP Outlook Pct])
			VAR _Wp = IF(ISBLANK([LP Word Pct]), 0, [LP Word Pct])
			VAR _Ep = IF(ISBLANK([LP Excel Pct]), 0, [LP Excel Pct])
			VAR _Pp = IF(ISBLANK([LP PowerPoint Pct]), 0, [LP PowerPoint Pct])
			VAR _Cp = IF(ISBLANK([LP Copilot Chat Pct V2]), 0, [LP Copilot Chat Pct V2])
			VAR _Sum = _Tp + _Op + _Wp + _Ep + _Pp + _Cp
			VAR _W = 220
			VAR _H = 20
			VAR _Tw = IF(_Sum > 0, ROUND(_Tp / _Sum * _W, 0), 0)
			VAR _Ow = IF(_Sum > 0, ROUND(_Op / _Sum * _W, 0), 0)
			VAR _Ww = IF(_Sum > 0, ROUND(_Wp / _Sum * _W, 0), 0)
			VAR _Ew = IF(_Sum > 0, ROUND(_Ep / _Sum * _W, 0), 0)
			VAR _Cw = IF(_Sum > 0, ROUND(_Cp / _Sum * _W, 0), 0)
			VAR _Pw = IF(_Sum > 0, _W - _Tw - _Ow - _Ww - _Ew - _Cw, 0)
			VAR _Ox = _Tw
			VAR _Wx = _Ox + _Ow
			VAR _Ex = _Wx + _Ww
			VAR _Px = _Ex + _Ew
			VAR _Cx = _Px + _Pw
			RETURN
			    IF(_Sum = 0, BLANK(),
			        "data:image/svg+xml;utf8," &
			        "<svg xmlns='http://www.w3.org/2000/svg' width='" & FORMAT(_W, "0") & "' height='" & FORMAT(_H, "0") & "'>" &
			        IF(_Tw > 0, "<rect x='0' y='0' width='" & FORMAT(_Tw, "0") & "' height='" & FORMAT(_H, "0") & "' fill='%236264A7'/>", "") &
			        IF(_Ow > 0, "<rect x='" & FORMAT(_Ox, "0") & "' y='0' width='" & FORMAT(_Ow, "0") & "' height='" & FORMAT(_H, "0") & "' fill='%230078D4'/>", "") &
			        IF(_Ww > 0, "<rect x='" & FORMAT(_Wx, "0") & "' y='0' width='" & FORMAT(_Ww, "0") & "' height='" & FORMAT(_H, "0") & "' fill='%232B579A'/>", "") &
			        IF(_Ew > 0, "<rect x='" & FORMAT(_Ex, "0") & "' y='0' width='" & FORMAT(_Ew, "0") & "' height='" & FORMAT(_H, "0") & "' fill='%23217346'/>", "") &
			        IF(_Pw > 0, "<rect x='" & FORMAT(_Px, "0") & "' y='0' width='" & FORMAT(_Pw, "0") & "' height='" & FORMAT(_H, "0") & "' fill='%23D24726'/>", "") &
			        IF(_Cw > 0, "<rect x='" & FORMAT(_Cx, "0") & "' y='0' width='" & FORMAT(_Cw, "0") & "' height='" & FORMAT(_H, "0") & "' fill='%237F85F5'/>", "") &
			        "</svg>"
			    )
		displayFolder: App Breakdown
		lineageTag: a1b2c3d4-e5f6-7890-abcd-ef1234567890
		dataCategory: ImageUrl

	/// Count of users per action category for the distribution bar chart
	measure 'LP Action Category Users' =
			VAR CurrentAction = SELECTEDVALUE('LP Action Categories'[ActionName])
			RETURN
			    COUNTROWS(
			        FILTER(
			            ALLSELECTED(SecDemEntraUsers),
			            [LP Action] = CurrentAction
			        )
			    )
		formatString: 0
		displayFolder: KPIs
		lineageTag: f1a2b3c4-d5e6-f7a8-b9c0-d1e2f3a4b5c6

	/// SVG rendering of 3 profile cards with app weight chips; highlights the selected profile with blue border
	measure 'LP Profile Cards SVG' =
			VAR Sel = SELECTEDVALUE('LP Weight Profiles'[ProfileName], "Balanced")
			VAR S1 = Sel = "Balanced"
			VAR S2 = Sel = "Collaboration Focus"
			VAR S3 = Sel = "Content Creation Focus"
			VAR SB = "%230078D4"
			VAR SBg = "%23EBF3FB"
			VAR DB = "%23D2D0CE"
			VAR DBg = "%23FFFFFF"
			VAR Card1 =
			    "<rect x='3' y='3' width='240' height='80' rx='8' fill='" & IF(S1,SBg,DBg) & "' stroke='" & IF(S1,SB,DB) & "' stroke-width='" & IF(S1,"2.5","1") & "'/>" &
			    IF(S1, "<circle cx='231' cy='15' r='5' fill='" & SB & "'/>", "") &
			    "<text x='15' y='21' font-size='11' font-weight='bold' fill='%23252423'>Balanced</text>" &
			    "<rect x='15' y='31' width='8' height='8' rx='2' fill='%236264A7'/><text x='26' y='39' font-size='9' fill='%23605E5C'>Teams 17%</text>" &
			    "<rect x='93' y='31' width='8' height='8' rx='2' fill='%230078D4'/><text x='104' y='39' font-size='9' fill='%23605E5C'>Outlook 17%</text>" &
			    "<rect x='181' y='31' width='8' height='8' rx='2' fill='%232B579A'/><text x='192' y='39' font-size='9' fill='%23605E5C'>Word 17%</text>" &
			    "<rect x='15' y='47' width='8' height='8' rx='2' fill='%23217346'/><text x='26' y='55' font-size='9' fill='%23605E5C'>Excel 17%</text>" &
			    "<rect x='93' y='47' width='8' height='8' rx='2' fill='%23D24726'/><text x='104' y='55' font-size='9' fill='%23605E5C'>PPT 16%</text>" &
			    "<rect x='181' y='47' width='8' height='8' rx='2' fill='%237F85F5'/><text x='192' y='55' font-size='9' fill='%23605E5C'>Copilot 16%</text>"
			VAR Card2 =
			    "<rect x='255' y='3' width='240' height='80' rx='8' fill='" & IF(S2,SBg,DBg) & "' stroke='" & IF(S2,SB,DB) & "' stroke-width='" & IF(S2,"2.5","1") & "'/>" &
			    IF(S2, "<circle cx='483' cy='15' r='5' fill='" & SB & "'/>", "") &
			    "<text x='267' y='21' font-size='11' font-weight='bold' fill='%23252423'>Collaboration Focus</text>" &
			    "<rect x='267' y='31' width='8' height='8' rx='2' fill='%236264A7'/><text x='278' y='39' font-size='9' fill='%23605E5C'>Teams 30%</text>" &
			    "<rect x='345' y='31' width='8' height='8' rx='2' fill='%230078D4'/><text x='356' y='39' font-size='9' fill='%23605E5C'>Outlook 30%</text>" &
			    "<rect x='433' y='31' width='8' height='8' rx='2' fill='%232B579A'/><text x='444' y='39' font-size='9' fill='%23605E5C'>Word 8%</text>" &
			    "<rect x='267' y='47' width='8' height='8' rx='2' fill='%23217346'/><text x='278' y='55' font-size='9' fill='%23605E5C'>Excel 8%</text>" &
			    "<rect x='345' y='47' width='8' height='8' rx='2' fill='%23D24726'/><text x='356' y='55' font-size='9' fill='%23605E5C'>PPT 8%</text>" &
			    "<rect x='433' y='47' width='8' height='8' rx='2' fill='%237F85F5'/><text x='444' y='55' font-size='9' fill='%23605E5C'>Copilot 16%</text>"
			VAR Card3 =
			    "<rect x='507' y='3' width='240' height='80' rx='8' fill='" & IF(S3,SBg,DBg) & "' stroke='" & IF(S3,SB,DB) & "' stroke-width='" & IF(S3,"2.5","1") & "'/>" &
			    IF(S3, "<circle cx='735' cy='15' r='5' fill='" & SB & "'/>", "") &
			    "<text x='519' y='21' font-size='11' font-weight='bold' fill='%23252423'>Content Creation Focus</text>" &
			    "<rect x='519' y='31' width='8' height='8' rx='2' fill='%236264A7'/><text x='530' y='39' font-size='9' fill='%23605E5C'>Teams 10%</text>" &
			    "<rect x='597' y='31' width='8' height='8' rx='2' fill='%230078D4'/><text x='608' y='39' font-size='9' fill='%23605E5C'>Outlook 10%</text>" &
			    "<rect x='685' y='31' width='8' height='8' rx='2' fill='%232B579A'/><text x='696' y='39' font-size='9' fill='%23605E5C'>Word 20%</text>" &
			    "<rect x='519' y='47' width='8' height='8' rx='2' fill='%23217346'/><text x='530' y='55' font-size='9' fill='%23605E5C'>Excel 20%</text>" &
			    "<rect x='597' y='47' width='8' height='8' rx='2' fill='%23D24726'/><text x='608' y='55' font-size='9' fill='%23605E5C'>PPT 20%</text>" &
			    "<rect x='685' y='47' width='8' height='8' rx='2' fill='%237F85F5'/><text x='696' y='55' font-size='9' fill='%23605E5C'>Copilot 20%</text>"
			RETURN
			    "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='750' height='88'>" &
			    Card1 & Card2 & Card3 &
			    "</svg>"
		displayFolder: Weights
		lineageTag: c3d4e5f6-a7b8-c9d0-e1f2-a3b4c5d6e7f8
		dataCategory: ImageUrl

	/// Inline SVG legend for app breakdown colors
	measure 'LP App Legend SVG' =
			"data:image/svg+xml;utf8," &
			"<svg xmlns='http://www.w3.org/2000/svg' width='560' height='16'>" &
			"<rect x='0' y='2' width='12' height='12' rx='2' fill='%236264A7'/><text x='16' y='12' font-size='11' fill='%23333'>Teams</text>" &
			"<rect x='70' y='2' width='12' height='12' rx='2' fill='%230078D4'/><text x='86' y='12' font-size='11' fill='%23333'>Outlook</text>" &
			"<rect x='155' y='2' width='12' height='12' rx='2' fill='%232B579A'/><text x='171' y='12' font-size='11' fill='%23333'>Word</text>" &
			"<rect x='225' y='2' width='12' height='12' rx='2' fill='%23217346'/><text x='241' y='12' font-size='11' fill='%23333'>Excel</text>" &
			"<rect x='295' y='2' width='12' height='12' rx='2' fill='%23D24726'/><text x='311' y='12' font-size='11' fill='%23333'>PowerPoint</text>" &
			"<rect x='400' y='2' width='12' height='12' rx='2' fill='%237F85F5'/><text x='416' y='12' font-size='11' fill='%23333'>Copilot Chat</text>" &
			"</svg>"
		displayFolder: App Breakdown
		lineageTag: a2b3c4d5-e6f7-a8b9-c0d1-e2f3a4b5c6d7
		dataCategory: ImageUrl

	/// Top 2 apps with Unicode block bars showing relative usage
	measure 'LP Top 2 Apps' =
			VAR Tp = IF(ISBLANK([LP Teams Pct]), 0, [LP Teams Pct])
			VAR Op = IF(ISBLANK([LP Outlook Pct]), 0, [LP Outlook Pct])
			VAR Wp = IF(ISBLANK([LP Word Pct]), 0, [LP Word Pct])
			VAR Ep = IF(ISBLANK([LP Excel Pct]), 0, [LP Excel Pct])
			VAR Pp = IF(ISBLANK([LP PowerPoint Pct]), 0, [LP PowerPoint Pct])
			VAR Cp = IF(ISBLANK([LP Copilot Chat Pct V2]), 0, [LP Copilot Chat Pct V2])
			VAR Total = [LP Weighted Total]
			VAR App1 =
			    SWITCH(
			        TRUE(),
			        Tp >= Op && Tp >= Wp && Tp >= Ep && Tp >= Pp && Tp >= Cp, "Teams",
			        Op >= Wp && Op >= Ep && Op >= Pp && Op >= Cp, "Outlook",
			        Wp >= Ep && Wp >= Pp && Wp >= Cp, "Word",
			        Ep >= Pp && Ep >= Cp, "Excel",
			        Pp >= Cp, "PPT",
			        "Copilot"
			    )
			VAR App1Val = SWITCH(App1, "Teams", Tp, "Outlook", Op, "Word", Wp, "Excel", Ep, "Copilot", Cp, Pp)
			VAR T2 = IF(App1 = "Teams", -1, Tp)
			VAR O2 = IF(App1 = "Outlook", -1, Op)
			VAR W2 = IF(App1 = "Word", -1, Wp)
			VAR E2 = IF(App1 = "Excel", -1, Ep)
			VAR P2 = IF(App1 = "PPT", -1, Pp)
			VAR C2 = IF(App1 = "Copilot", -1, Cp)
			VAR App2 =
			    SWITCH(
			        TRUE(),
			        T2 >= O2 && T2 >= W2 && T2 >= E2 && T2 >= P2 && T2 >= C2, "Teams",
			        O2 >= W2 && O2 >= E2 && O2 >= P2 && O2 >= C2, "Outlook",
			        W2 >= E2 && W2 >= P2 && W2 >= C2, "Word",
			        E2 >= P2 && E2 >= C2, "Excel",
			        P2 >= C2, "PPT",
			        "Copilot"
			    )
			VAR App2Val = SWITCH(App2, "Teams", Tp, "Outlook", Op, "Word", Wp, "Excel", Ep, "Copilot", Cp, Pp)
			VAR F1 = MAX(0, MIN(8, ROUND(App1Val * 8, 0)))
			VAR Bar1 = REPT("█", F1) & REPT("░", 8 - F1)
			VAR F2 = MAX(0, MIN(8, ROUND(App2Val * 8, 0)))
			VAR Bar2 = REPT("█", F2) & REPT("░", 8 - F2)
			RETURN
			    IF(
			        ISBLANK(Total) || Total = 0,
			        BLANK(),
			        Bar1 & " " & App1 & " " & FORMAT(App1Val, "0%") & "   " & Bar2 & " " & App2 & " " & FORMAT(App2Val, "0%")
			    )
		displayFolder: App Breakdown
		lineageTag: d4e5f6a7-b8c9-d0e1-f2a3-b4c5d6e7f8a9

	/// Dynamic title for Teams weight slicer
	measure 'LP Teams Weight Title' = "Teams: " & FORMAT([LP Teams Weight], "0%")
		isHidden
		displayFolder: Weights
		lineageTag: a1111111-1111-1111-1111-111111111111

	/// Dynamic title for Outlook weight slicer
	measure 'LP Outlook Weight Title' = "Outlook: " & FORMAT([LP Outlook Weight], "0%")
		isHidden
		displayFolder: Weights
		lineageTag: a2222222-2222-2222-2222-222222222222

	/// Dynamic title for Word weight slicer
	measure 'LP Word Weight Title' = "Word: " & FORMAT([LP Word Weight], "0%")
		isHidden
		displayFolder: Weights
		lineageTag: a3333333-3333-3333-3333-333333333333

	/// Dynamic title for Excel weight slicer
	measure 'LP Excel Weight Title' = "Excel: " & FORMAT([LP Excel Weight], "0%")
		isHidden
		displayFolder: Weights
		lineageTag: a4444444-4444-4444-4444-444444444444

	/// Dynamic title for PowerPoint weight slicer
	measure 'LP PowerPoint Weight Title' = "PPT: " & FORMAT([LP PowerPoint Weight], "0%")
		isHidden
		displayFolder: Weights
		lineageTag: a5555555-5555-5555-5555-555555555555

	/// Sum of the 5 custom weight slicer values (should equal 100 for valid config)
	measure 'LP Custom Weight Sum' =
			VAR T = SELECTEDVALUE('Teams Weight %'[Teams Weight], 17)
			VAR O = SELECTEDVALUE('Outlook Weight %'[Outlook Weight %], 17)
			VAR W = SELECTEDVALUE('Word Weight %'[Word Weight %], 17)
			VAR E = SELECTEDVALUE('Excel Weight %'[Excel Weight %], 17)
			VAR P = SELECTEDVALUE('PowerPoint Weight %'[PowerPoint Weight %], 16)
			VAR C = SELECTEDVALUE('Copilot Chat Weight %'[Copilot Chat Weight %], 16)
			RETURN T + O + W + E + P + C
		formatString: 0
		isHidden
		displayFolder: Weights
		lineageTag: b1111111-1111-1111-1111-111111111111

	/// Status text showing whether custom weights sum to 100% (only shows for Custom profile)
	measure 'LP Custom Weight Status' =
			VAR Profile = SELECTEDVALUE('LP Weight Profiles'[ProfileName])
			VAR IsCustom = Profile = "Custom" || ISBLANK(Profile)
			VAR Total = [LP Custom Weight Sum]
			RETURN
			    IF(
			        NOT(IsCustom),
			        "",
			        IF(Total = 100, "✓ Total: 100%", "⚠ Total: " & FORMAT(Total, "0") & "% — must equal 100%")
			    )
		displayFolder: Weights
		lineageTag: b2222222-2222-2222-2222-222222222222

	/// Returns TRUE when Custom profile is selected (or no profile), used for conditional visibility of weight slicers
	measure 'LP Show Custom Slicers' =
			VAR Profile = SELECTEDVALUE('LP Weight Profiles'[ProfileName])
			RETURN IF(Profile = "Custom" || ISBLANK(Profile), TRUE(), FALSE())
		isHidden
		displayFolder: Weights
		lineageTag: c1111111-1111-1111-1111-111111111111

	/// Returns the currently selected profile name, defaults to Balanced
	measure 'LP Active Profile' = SELECTEDVALUE('LP Weight Profiles'[ProfileName], "Balanced")
		isHidden
		displayFolder: Weights
		lineageTag: 5ac7995e-c7c0-4044-9986-8e421095975a

	/// Returns 1 when user's action matches the selected LP Action Category (or 1 when no category selected). Used as visual-level filter for cross-filtering.
	measure 'LP Action Filter Match' =
			VAR SelectedAction = SELECTEDVALUE('LP Action Categories'[ActionName])
			RETURN
			    IF(
			        ISBLANK(SelectedAction),
			        1,
			        IF([LP Action] = SelectedAction, 1, 0)
			    )
		displayFolder: Scoring
		lineageTag: f574bc62-5e0d-4536-bfcd-d0d2f1e8fbf9

	/// Copilot Chat weight resolved from selected profile or manual slicer
	measure 'LP Copilot Chat Weight' =
			VAR Profile = SELECTEDVALUE('LP Weight Profiles'[ProfileName])
			RETURN
			    SWITCH(
			        Profile,
			        "Balanced", 0.16,
			        "Collaboration Focus", 0.16,
			        "Content Creation Focus", 0.20,
			        SELECTEDVALUE('Copilot Chat Weight %'[Copilot Chat Weight %], 16) / 100
			    )
		formatString: 0%
		displayFolder: Weights
		lineageTag: 874f3205-0bf1-4850-9497-280b4fe8658f

	/// Copilot Chat raw activity * LP weight
	measure 'LP Copilot Chat Weighted' =
			VAR Raw =
			    SUMX(
			        RELATEDTABLE('SecDemoM365Usage'),
			        IF(
			            'SecDemoM365Usage'[Operation] = "CopilotInteraction",
			            1, 0
			        )
			    )
			RETURN Raw * [LP Copilot Chat Weight]
		isHidden
		displayFolder: App Scores
		lineageTag: 887b3f3a-8ae2-4da6-a1d0-515de7dc3c74

	/// Dynamic title for Copilot Chat weight slicer
	measure 'LP Copilot Chat Weight Title' = "Copilot Chat: " & FORMAT([LP Copilot Chat Weight], "0%")
		isHidden
		displayFolder: Weights
		lineageTag: 2d47dc3e-c201-43ed-abef-945af88cd501

	/// Percentile rank for Copilot Chat activity among active users (0-1, RANKX-based)
	measure 'LP Copilot Chat Pct V2' =
			VAR ActiveUsers = FILTER(ALLSELECTED(SecDemEntraUsers), [LP Weighted Total] > 0)
			VAR Total = COUNTROWS(ActiveUsers)
			VAR Rnk = RANKX(ActiveUsers, [LP Copilot Chat Weighted], , ASC, Skip)
			RETURN IF(Total > 0 && [LP Weighted Total] > 0, DIVIDE(Rnk, Total), BLANK())
		formatString: 0%
		displayFolder: App Breakdown
		lineageTag: 2797c03d-1ed3-4d28-8bbf-1e64c0de27c4

	/// Copilot Chat usage percentile - RANKX-based among Copilot-active users (0-100%)
	measure 'LP Copilot Chat Pct' =
			VAR UserCopilot = CALCULATE(COUNTROWS('SecDemoM365Usage'), 'SecDemoM365Usage'[Operation] = "CopilotInteraction")
			VAR ActiveCopilotUsers = FILTER(ALLSELECTED(SecDemEntraUsers), CALCULATE(COUNTROWS('SecDemoM365Usage'), 'SecDemoM365Usage'[Operation] = "CopilotInteraction") > 0)
			VAR Total = COUNTROWS(ActiveCopilotUsers)
			VAR Rnk = RANKX(ActiveCopilotUsers, CALCULATE(COUNTROWS('SecDemoM365Usage'), 'SecDemoM365Usage'[Operation] = "CopilotInteraction"), , ASC, Skip)
			RETURN IF(Total > 0 && UserCopilot > 0, DIVIDE(Rnk, Total), BLANK())
		formatString: 0%
		displayFolder: App Breakdown
		lineageTag: aa0f8c68-189d-4977-a7b6-bed0f7e0bef7

	column Placeholder
		lineageTag: d7b5a9a9-199f-49b6-9902-ccd39dc2f3a7
		isNameInferred
		sourceColumn: [Placeholder]

	partition 'LP Measures' = calculated
		mode: import
		source = ROW("Placeholder", 0)

