table 'M365 ActiveDaysSummary'
	lineageTag: 326150f0-bf57-459d-8a63-89ac531cca62

	measure 'All Users Count' = COUNTROWS(SecDemEntraUsers)
		formatString: 0
		lineageTag: 01837589-d7ae-40d6-9c2d-ebc1654e6c19

	measure 'Total Teams Active Days' = SUM('M365 ActiveDaysSummary'[TeamsActiveDays])
		formatString: 0
		lineageTag: eccd201d-5089-452f-99f4-370e7c9a2b5f

	measure 'Total Outlook Active Days' = SUM('M365 ActiveDaysSummary'[OutlookActiveDays])
		formatString: 0
		lineageTag: 9d786fc6-7d13-4712-a4d3-5fa43653f71b

	measure 'Total Word Active Days' = SUM('M365 ActiveDaysSummary'[WordActiveDays])
		formatString: 0
		lineageTag: 9b855a9c-9132-4980-a55d-1e9a1efae100

	measure 'Total Excel Active Days' = SUM('M365 ActiveDaysSummary'[ExcelActiveDays])
		formatString: 0
		lineageTag: 561c7757-8955-4728-98af-342895674c58

	measure 'Total PowerPoint Active Days' = SUM('M365 ActiveDaysSummary'[PowerPointActiveDays])
		formatString: 0
		lineageTag: 7da86305-9d19-4c72-838f-b3317bb824e3

	measure 'Avg Teams Active Days Per User' = AVERAGE('M365 ActiveDaysSummary'[TeamsActiveDays])
		lineageTag: eb910e63-a87a-4e35-bf00-6cc9f1d76c1e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Avg Outlook Active Days Per User' = AVERAGE('M365 ActiveDaysSummary'[OutlookActiveDays])
		lineageTag: b610ad34-5566-45e4-9d10-7e3fd6085f1a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Avg M365 Active Days Per User' = ```
			
			AVERAGEX(
			    'M365 ActiveDaysSummary',
			    'M365 ActiveDaysSummary'[TeamsActiveDays] + 
			    'M365 ActiveDaysSummary'[OutlookActiveDays] + 
			    'M365 ActiveDaysSummary'[WordActiveDays] + 
			    'M365 ActiveDaysSummary'[ExcelActiveDays] + 
			    'M365 ActiveDaysSummary'[PowerPointActiveDays]
			)
			```
		lineageTag: c878728a-0b4c-4c68-94c3-36dba4f54621

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Actions Per Week' =
			
			VAR TotalActions = [M365 All Apps Total V2]
			VAR MinDate = MIN(SecDemoM365Usage[CreationTime])
			VAR MaxDate = MAX(SecDemoM365Usage[CreationTime])
			VAR TotalWeeks = MAX(DATEDIFF(MinDate, MaxDate, WEEK), 1)
			RETURN
			DIVIDE(TotalActions, TotalWeeks, 0)
		lineageTag: c10a7aab-dd83-414f-99e6-2cf2dd97191d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Avg Active Days Per User Per Week' = ```
			
			VAR MinDate = MIN(SecDemoM365Usage[CreationTime])
			VAR MaxDate = MAX(SecDemoM365Usage[CreationTime])
			VAR TotalWeeks = MAX(DATEDIFF(MinDate, MaxDate, WEEK), 1)
			VAR TotalUsers = COUNTROWS('M365 ActiveDaysSummary')
			
			// Total unique active days across all users (entire period)
			VAR TotalUniqueActiveDays = 
			    SUMX(
			        'M365 ActiveDaysSummary',
			        MAX(
			            'M365 ActiveDaysSummary'[TeamsActiveDays],
			            MAX(
			                'M365 ActiveDaysSummary'[OutlookActiveDays],
			                MAX(
			                    'M365 ActiveDaysSummary'[WordActiveDays],
			                    MAX(
			                        'M365 ActiveDaysSummary'[ExcelActiveDays],
			                        'M365 ActiveDaysSummary'[PowerPointActiveDays]
			                    )
			                )
			            )
			        )
			    )
			
			// Average per user per week
			RETURN
			DIVIDE(TotalUniqueActiveDays, TotalWeeks * TotalUsers, 0)
			```
		lineageTag: 93ded2e3-7cbf-4d97-a79d-9280681081ec

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Actions Per Week Per User' =
			
			VAR TotalActions = [M365 All Apps Total V2]
			VAR MinDate = MIN(SecDemoM365Usage[CreationTime])
			VAR MaxDate = MAX(SecDemoM365Usage[CreationTime])
			VAR TotalWeeks = MAX(DATEDIFF(MinDate, MaxDate, WEEK), 1)
			VAR TotalUsers = DISTINCTCOUNT(SecDemEntraUsers[userPrincipalName])
			RETURN
			DIVIDE(TotalActions, TotalWeeks * TotalUsers, 0)
		lineageTag: f3f7e7a0-8ff9-410f-afbc-3e1877c35077

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Teams Active Days Per Week' =
			
			VAR TotalDays = SUM('M365 ActiveDaysSummary'[TeamsActiveDays])
			VAR MinDate = MIN(SecDemoM365Usage[CreationTime])
			VAR MaxDate = MAX(SecDemoM365Usage[CreationTime])
			VAR TotalWeeks = MAX(DATEDIFF(MinDate, MaxDate, WEEK), 1)
			RETURN
			DIVIDE(TotalDays, TotalWeeks, 0)
		lineageTag: 25cd807f-4a50-43de-b1a5-6e9c72673bd6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Outlook Active Days Per Week' =
			
			VAR TotalDays = SUM('M365 ActiveDaysSummary'[OutlookActiveDays])
			VAR MinDate = MIN(SecDemoM365Usage[CreationTime])
			VAR MaxDate = MAX(SecDemoM365Usage[CreationTime])
			VAR TotalWeeks = MAX(DATEDIFF(MinDate, MaxDate, WEEK), 1)
			RETURN
			DIVIDE(TotalDays, TotalWeeks, 0)
		lineageTag: ec03c1ac-93fa-42bc-b2f9-cbd9621ce075

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Active Days Per Week by App' = ```
			
			VAR SelectedApp = SELECTEDVALUE('App Actions Table'[AppName])
			VAR MinDate = MIN(SecDemoM365Usage[CreationTime])
			VAR MaxDate = MAX(SecDemoM365Usage[CreationTime])
			VAR TotalWeeks = MAX(DATEDIFF(MinDate, MaxDate, WEEK), 1)
			VAR TotalDays = 
			    SWITCH(
			        SelectedApp,
			        "Teams", SUM('M365 ActiveDaysSummary'[TeamsActiveDays]),
			        "Outlook", SUM('M365 ActiveDaysSummary'[OutlookActiveDays]),
			        "Word", SUM('M365 ActiveDaysSummary'[WordActiveDays]),
			        "Excel", SUM('M365 ActiveDaysSummary'[ExcelActiveDays]),
			        "PowerPoint", SUM('M365 ActiveDaysSummary'[PowerPointActiveDays]),
			        BLANK()
			    )
			RETURN
			DIVIDE(TotalDays, TotalWeeks, 0)
			```
		lineageTag: b2b417d2-8c38-4b4a-8538-2ac2ff998ff3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Active Days Per User Per Week by App' = ```
			
			VAR SelectedApp = SELECTEDVALUE('App Actions Table'[AppName])
			VAR MinDate = MIN(SecDemoM365Usage[CreationTime])
			VAR MaxDate = MAX(SecDemoM365Usage[CreationTime])
			VAR TotalWeeks = MAX(DATEDIFF(MinDate, MaxDate, WEEK), 1)
			VAR TotalUsers = COUNTROWS('M365 ActiveDaysSummary')
			
			VAR TotalDays = 
			    SWITCH(
			        SelectedApp,
			        "Teams", SUM('M365 ActiveDaysSummary'[TeamsActiveDays]),
			        "Outlook", SUM('M365 ActiveDaysSummary'[OutlookActiveDays]),
			        "Word", SUM('M365 ActiveDaysSummary'[WordActiveDays]),
			        "Excel", SUM('M365 ActiveDaysSummary'[ExcelActiveDays]),
			        "PowerPoint", SUM('M365 ActiveDaysSummary'[PowerPointActiveDays]),
			        BLANK()
			    )
			
			RETURN
			DIVIDE(TotalDays, TotalWeeks * TotalUsers, 0)
			```
		lineageTag: ad27da6c-de30-4dfb-9f74-50df27554388

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Licensed Active Days Per User Per Week' = ```
			
			VAR MinDate = MIN(SecDemoM365Usage[CreationTime])
			VAR MaxDate = MAX(SecDemoM365Usage[CreationTime])
			VAR TotalWeeks = MAX(DATEDIFF(MinDate, MaxDate, WEEK), 1)
			VAR LicensedUsers = COUNTROWS(FILTER('M365 ActiveDaysSummary', 'M365 ActiveDaysSummary'[Copilot License Status] = "Licensed"))
			
			VAR TotalDays = 
			    SUMX(
			        FILTER('M365 ActiveDaysSummary', 'M365 ActiveDaysSummary'[Copilot License Status] = "Licensed"),
			        MAX(
			            'M365 ActiveDaysSummary'[TeamsActiveDays],
			            MAX(
			                'M365 ActiveDaysSummary'[OutlookActiveDays],
			                MAX(
			                    'M365 ActiveDaysSummary'[WordActiveDays],
			                    MAX(
			                        'M365 ActiveDaysSummary'[ExcelActiveDays],
			                        'M365 ActiveDaysSummary'[PowerPointActiveDays]
			                    )
			                )
			            )
			        )
			    )
			
			RETURN
			DIVIDE(TotalDays, TotalWeeks * LicensedUsers, 0)
			```
		lineageTag: 80bb6084-7a38-4f3f-9587-854d4e836acd

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Unlicensed Active Days Per User Per Week' = ```
			
			VAR MinDate = MIN(SecDemoM365Usage[CreationTime])
			VAR MaxDate = MAX(SecDemoM365Usage[CreationTime])
			VAR TotalWeeks = MAX(DATEDIFF(MinDate, MaxDate, WEEK), 1)
			VAR UnlicensedUsers = COUNTROWS(FILTER('M365 ActiveDaysSummary', 'M365 ActiveDaysSummary'[Copilot License Status] = "Unlicensed"))
			
			VAR TotalDays = 
			    SUMX(
			        FILTER('M365 ActiveDaysSummary', 'M365 ActiveDaysSummary'[Copilot License Status] = "Unlicensed"),
			        MAX(
			            'M365 ActiveDaysSummary'[TeamsActiveDays],
			            MAX(
			                'M365 ActiveDaysSummary'[OutlookActiveDays],
			                MAX(
			                    'M365 ActiveDaysSummary'[WordActiveDays],
			                    MAX(
			                        'M365 ActiveDaysSummary'[ExcelActiveDays],
			                        'M365 ActiveDaysSummary'[PowerPointActiveDays]
			                    )
			                )
			            )
			        )
			    )
			
			RETURN
			DIVIDE(TotalDays, TotalWeeks * UnlicensedUsers, 0)
			```
		lineageTag: ff5df857-b289-45cc-8081-c2677a38bf31

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Active Users by Month' = ```
			
			CALCULATE(
			    DISTINCTCOUNT(SecDemoM365Usage[UserId]),
			    FILTER(
			        SecDemoM365Usage,
			        VAR IsOfficeFile = 
			            LOWER(SecDemoM365Usage[SourceFileExtension]) IN { "docx", "doc", "dotx", "xlsx", "xls", "xlsm", "csv", "pptx", "ppt", "ppsx" } &&
			            (SecDemoM365Usage[Operation] IN { "FileViewed", "FileModified", "FileDownloaded", "FileUploaded" })
			        VAR IsExchange = 
			            SecDemoM365Usage[Workload] = "Exchange" && 
			            SecDemoM365Usage[Operation] IN { "Send", "MailItemsAccessed" }
			        VAR IsTeams = 
			            SecDemoM365Usage[Workload] = "MicrosoftTeams" && 
			            SecDemoM365Usage[Operation] IN { "MessageSent", "MessageRead", "MeetingParticipantJoined" }
			        RETURN
			            IsOfficeFile || IsExchange || IsTeams
			    )
			)
			```
		formatString: 0
		lineageTag: 46d19c76-087d-436d-bb30-0552252de645

	measure 'Total Actions by Month' = ```
			
			SUMX(
			    SecDemoM365Usage,
			    VAR IsOfficeFile = 
			        LOWER(SecDemoM365Usage[SourceFileExtension]) IN { "docx", "doc", "dotx", "xlsx", "xls", "xlsm", "csv", "pptx", "ppt", "ppsx" } &&
			        (SecDemoM365Usage[Operation] IN { "FileViewed", "FileModified", "FileDownloaded", "FileUploaded" })
			    VAR IsExchange = 
			        SecDemoM365Usage[Workload] = "Exchange" && 
			        SecDemoM365Usage[Operation] IN { "Send", "MailItemsAccessed" }
			    VAR IsTeams = 
			        SecDemoM365Usage[Workload] = "MicrosoftTeams" && 
			        SecDemoM365Usage[Operation] IN { "MessageSent", "MessageRead", "MeetingParticipantJoined" }
			    RETURN
			        IF(IsOfficeFile || IsExchange || IsTeams, 1, 0)
			)
			```
		formatString: 0
		lineageTag: 42129d66-727f-484f-a010-2edee188a8d9

	column UserId
		lineageTag: aee93be9-c8c0-42d2-a80d-0f7eb3e53329
		summarizeBy: none
		isNameInferred
		sourceColumn: SecDemoM365Usage[UserId]

		annotation SummarizationSetBy = Automatic

	column TeamsActiveDays
		formatString: 0
		lineageTag: b5132192-1e51-4dde-ad79-085be604664d
		summarizeBy: sum
		isNameInferred
		sourceColumn: [TeamsActiveDays]

		annotation SummarizationSetBy = Automatic

	column OutlookActiveDays
		formatString: 0
		lineageTag: 609da530-c27c-46cd-a166-f0ee580d9a02
		summarizeBy: sum
		isNameInferred
		sourceColumn: [OutlookActiveDays]

		annotation SummarizationSetBy = Automatic

	column WordActiveDays
		formatString: 0
		lineageTag: 4a4c951d-76b2-4628-8ee6-419a80196961
		summarizeBy: sum
		isNameInferred
		sourceColumn: [WordActiveDays]

		annotation SummarizationSetBy = Automatic

	column ExcelActiveDays
		formatString: 0
		lineageTag: 63df1720-ca4b-4d1a-910c-a86308e34708
		summarizeBy: sum
		isNameInferred
		sourceColumn: [ExcelActiveDays]

		annotation SummarizationSetBy = Automatic

	column PowerPointActiveDays
		formatString: 0
		lineageTag: 9cc87fff-60da-44a6-b26a-8e8e89122fad
		summarizeBy: sum
		isNameInferred
		sourceColumn: [PowerPointActiveDays]

		annotation SummarizationSetBy = Automatic

	column TeamsActivityCount
		formatString: 0
		lineageTag: 13df4432-c85b-4c7d-8ed1-52319b66422c
		summarizeBy: sum
		isNameInferred
		sourceColumn: [TeamsActivityCount]

		annotation SummarizationSetBy = Automatic

	column OutlookActivityCount
		formatString: 0
		lineageTag: 33fbd0ce-5c4d-4e9f-8f8a-9ea21486ca2e
		summarizeBy: sum
		isNameInferred
		sourceColumn: [OutlookActivityCount]

		annotation SummarizationSetBy = Automatic

	column OfficeFilesActivityCount
		formatString: 0
		lineageTag: 37a62a1b-4dcb-4e6c-be68-d34b51175808
		summarizeBy: sum
		isNameInferred
		sourceColumn: [OfficeFilesActivityCount]

		annotation SummarizationSetBy = Automatic

	column 'Teams Activity Segment'
		lineageTag: bda4159f-efd6-4623-90e8-61e8a90f3452
		summarizeBy: none
		isNameInferred
		sourceColumn: [Teams Activity Segment]

		annotation SummarizationSetBy = Automatic

	column 'Outlook Activity Segment'
		lineageTag: 9577d91b-ee92-4e3a-ac8f-fb33555a406a
		summarizeBy: none
		isNameInferred
		sourceColumn: [Outlook Activity Segment]

		annotation SummarizationSetBy = Automatic

	column 'Office Files Activity Segment'
		lineageTag: 1bf9813e-74bb-4902-88b6-934789e4db12
		summarizeBy: none
		isNameInferred
		sourceColumn: [Office Files Activity Segment]

		annotation SummarizationSetBy = Automatic

	column 'Overall M365 Activity Segment'
		lineageTag: 61dd9e22-b515-453e-a26c-696854dd874f
		summarizeBy: none
		isNameInferred
		sourceColumn: [Overall M365 Activity Segment]

		annotation SummarizationSetBy = Automatic

	column 'Word Activity Segment'
		lineageTag: afe2cd03-cc6f-49c1-8345-54ceb96d7e83
		summarizeBy: none
		isNameInferred
		sourceColumn: [Word Activity Segment]

		annotation SummarizationSetBy = Automatic

	column 'Excel Activity Segment'
		lineageTag: f433e73a-e646-43df-a272-dbf332faa43c
		summarizeBy: none
		isNameInferred
		sourceColumn: [Excel Activity Segment]

		annotation SummarizationSetBy = Automatic

	column 'PowerPoint Activity Segment'
		lineageTag: a9cba5ae-8690-469a-80ae-6c3fdf7d19dd
		summarizeBy: none
		isNameInferred
		sourceColumn: [PowerPoint Activity Segment]

		annotation SummarizationSetBy = Automatic

	column 'Copilot License Status'
		lineageTag: e1242178-2d3f-45be-aab0-7d12e3e7593f
		summarizeBy: none
		isNameInferred
		sourceColumn: [Copilot License Status]

		annotation SummarizationSetBy = Automatic

	partition 'M365 ActiveDaysSummary' = calculated
		mode: import
		source = ```
				
				VAR BaseTable = 
				    ADDCOLUMNS(
				        SUMMARIZE(
				            'SecDemoM365Usage',
				            'SecDemoM365Usage'[UserId]
				        ),
				        "TeamsActiveDays", 
				            CALCULATE(
				                DISTINCTCOUNT('SecDemoM365Usage'[CreationDate]),
				                'SecDemoM365Usage'[Workload] = "MicrosoftTeams",
				                'SecDemoM365Usage'[Operation] IN {"MessageSent", "MessageRead", "MeetingParticipantJoined"}
				            ),
				        "OutlookActiveDays",
				            CALCULATE(
				                DISTINCTCOUNT('SecDemoM365Usage'[CreationDate]),
				                'SecDemoM365Usage'[Workload] = "Exchange",
				                'SecDemoM365Usage'[Operation] IN {"Send", "MailItemsAccessed"}
				            ),
				        "WordActiveDays",
				            CALCULATE(
				                DISTINCTCOUNT('SecDemoM365Usage'[CreationDate]),
				                LOWER('SecDemoM365Usage'[SourceFileExtension]) IN {"docx", "doc", "dotx"},
				                'SecDemoM365Usage'[Operation] IN {"FileViewed", "FileModified", "FileDownloaded", "FileUploaded"}
				            ),
				        "ExcelActiveDays",
				            CALCULATE(
				                DISTINCTCOUNT('SecDemoM365Usage'[CreationDate]),
				                LOWER('SecDemoM365Usage'[SourceFileExtension]) IN {"xlsx", "xls", "xlsm", "csv"},
				                'SecDemoM365Usage'[Operation] IN {"FileViewed", "FileModified", "FileDownloaded", "FileUploaded"}
				            ),
				        "PowerPointActiveDays",
				            CALCULATE(
				                DISTINCTCOUNT('SecDemoM365Usage'[CreationDate]),
				                LOWER('SecDemoM365Usage'[SourceFileExtension]) IN {"pptx", "ppt", "ppsx"},
				                'SecDemoM365Usage'[Operation] IN {"FileViewed", "FileModified", "FileDownloaded", "FileUploaded"}
				            ),
				        "TeamsActivityCount",
				            CALCULATE(
				                COUNTROWS('SecDemoM365Usage'),
				                'SecDemoM365Usage'[Workload] = "MicrosoftTeams",
				                'SecDemoM365Usage'[Operation] IN {"MessageSent", "MessageRead", "MeetingParticipantJoined"}
				            ),
				        "OutlookActivityCount",
				            CALCULATE(
				                COUNTROWS('SecDemoM365Usage'),
				                'SecDemoM365Usage'[Workload] = "Exchange",
				                'SecDemoM365Usage'[Operation] IN {"Send", "MailItemsAccessed", "MailboxLogin"}
				            ),
				        "OfficeFilesActivityCount",
				            CALCULATE(
				                COUNTROWS('SecDemoM365Usage'),
				                LOWER('SecDemoM365Usage'[SourceFileExtension]) IN {"docx", "doc", "dotx", "xlsx", "xls", "xlsm", "csv", "pptx", "ppt", "ppsx"},
				                'SecDemoM365Usage'[Operation] IN {"FileViewed", "FileModified", "FileDownloaded", "FileUploaded"}
				            ),
				        "Copilot License Status",
				              VAR UserEmail = 'SecDemoM365Usage'[UserId]
				              RETURN
				             IF(
				                  LOOKUPVALUE(
				                     'SecDemEntraUsers'[hasLicense],
				                     'SecDemEntraUsers'[UserPrincipalName], UserEmail
				             ) = TRUE(),
				             "Licensed",
				             "Unlicensed"
				    )
				            )
				
				RETURN
				ADDCOLUMNS(
				    FILTER(
				        BaseTable,
				        [TeamsActiveDays] + [OutlookActiveDays] + [WordActiveDays] + [ExcelActiveDays] + [PowerPointActiveDays] > 0
				    ),
				    "Teams Activity Segment",
				        IF(
				            [TeamsActiveDays] > 0,
				            SWITCH(
				                TRUE(),
				                [TeamsActiveDays] <= 5, "1. 1-5 Days (Infrequent)",
				                [TeamsActiveDays] <= 10, "2. 6-10 Days (Moderate)",
				                [TeamsActiveDays] <= 19, "3. 11-19 Days (Frequent)",
				                "4. 20+ Days (Daily)"
				            ),
				            "0. No Usage"
				        ),
				    "Outlook Activity Segment",
				        IF(
				            [OutlookActiveDays] > 0,
				            SWITCH(
				                TRUE(),
				                [OutlookActiveDays] <= 5, "1. 1-5 Days (Infrequent)",
				                [OutlookActiveDays] <= 10, "2. 6-10 Days (Moderate)",
				                [OutlookActiveDays] <= 19, "3. 11-19 Days (Frequent)",
				                "4. 20+ Days (Daily)"
				            ),
				            "0. No Usage"
				        ),
				    "Word Activity Segment",
				        IF(
				            [WordActiveDays] > 0,
				            SWITCH(
				                TRUE(),
				                [WordActiveDays] <= 5, "1. 1-5 Days (Infrequent)",
				                [WordActiveDays] <= 10, "2. 6-10 Days (Moderate)",
				                [WordActiveDays] <= 19, "3. 11-19 Days (Frequent)",
				                "4. 20+ Days (Daily)"
				            ),
				            "0. No Usage"
				        ),
				    "Excel Activity Segment",
				        IF(
				            [ExcelActiveDays] > 0,
				            SWITCH(
				                TRUE(),
				                [ExcelActiveDays] <= 5, "1. 1-5 Days (Infrequent)",
				                [ExcelActiveDays] <= 10, "2. 6-10 Days (Moderate)",
				                [ExcelActiveDays] <= 19, "3. 11-19 Days (Frequent)",
				                "4. 20+ Days (Daily)"
				            ),
				            "0. No Usage"
				        ),
				    "PowerPoint Activity Segment",
				        IF(
				            [PowerPointActiveDays] > 0,
				            SWITCH(
				                TRUE(),
				                [PowerPointActiveDays] <= 5, "1. 1-5 Days (Infrequent)",
				                [PowerPointActiveDays] <= 10, "2. 6-10 Days (Moderate)",
				                [PowerPointActiveDays] <= 19, "3. 11-19 Days (Frequent)",
				                "4. 20+ Days (Daily)"
				            ),
				            "0. No Usage"
				        ),
				    "Office Files Activity Segment",
				        VAR OfficeActiveDays = [WordActiveDays] + [ExcelActiveDays] + [PowerPointActiveDays]
				        RETURN
				        IF(
				            OfficeActiveDays > 0,
				            SWITCH(
				                TRUE(),
				                OfficeActiveDays <= 5, "1. 1-5 Days (Infrequent)",
				                OfficeActiveDays <= 10, "2. 6-10 Days (Moderate)",
				                OfficeActiveDays <= 19, "3. 11-19 Days (Frequent)",
				                "4. 20+ Days (Daily)"
				            ),
				            "0. No Usage"
				        ),
				    "Overall M365 Activity Segment",
				        VAR TotalActiveDays = [TeamsActiveDays] + [OutlookActiveDays] + [WordActiveDays] + [ExcelActiveDays] + [PowerPointActiveDays]
				        RETURN
				        IF(
				            TotalActiveDays > 0,
				            SWITCH(
				                TRUE(),
				                TotalActiveDays <= 5, "1. 1-5 Days (Infrequent)",
				                TotalActiveDays <= 10, "2. 6-10 Days (Moderate)",
				                TotalActiveDays <= 19, "3. 11-19 Days (Frequent)",
				                "4. 20+ Days (Daily)"
				            ),
				            "0. No Usage"
				        )
				)
				```

	annotation PBI_Id = 100f2d1e72c641068eefb01ef4ea15ed

