table 'Outlook Weight %'
	lineageTag: 1813cc10-aa93-4a25-867e-6b901d5193d6

	measure 'Outlook Weight % Value' = SELECTEDVALUE('Outlook Weight %'[Outlook Weight %], 30)
		formatString: 0
		lineageTag: d256fbfb-a0ad-4532-833a-7affe04379d2

	column 'Outlook Weight %'
		formatString: 0
		lineageTag: cc82dd82-57d9-4956-ade5-3d7bd34467d7
		summarizeBy: none
		sourceColumn: [Value]

		extendedProperty ParameterMetadata =
				{
				  "version": 0
				}

		annotation SummarizationSetBy = User

	partition 'Outlook Weight %' = calculated
		mode: import
		source = GENERATESERIES(0, 100, 1)

	annotation PBI_Id = cfe4bc0531a24d6abe4a6bcf3a8fdb79

