table 'PowerPoint Weight %'
	lineageTag: 20c9e049-22f5-473e-adcf-e876b0189b33

	measure 'PowerPoint Weight % Value' = SELECTEDVALUE('PowerPoint Weight %'[PowerPoint Weight %], 10)
		formatString: 0
		lineageTag: 10aa18f8-3ad5-4224-89f2-313c1122f973

	column 'PowerPoint Weight %'
		formatString: 0
		lineageTag: 83497ab0-c897-4e93-a709-209ce0772b78
		summarizeBy: none
		sourceColumn: [Value]

		extendedProperty ParameterMetadata =
				{
				  "version": 0
				}

		annotation SummarizationSetBy = User

	partition 'PowerPoint Weight %' = calculated
		mode: import
		source = GENERATESERIES(0, 100, 1)

	annotation PBI_Id = e2d86bb4707142a0ade04262819e0dc5

