table 'Teams Weight %'
	lineageTag: 7387c726-3a80-4d57-8010-3a620a14e8c4

	measure 'Teams Weight Value' = SELECTEDVALUE('Teams Weight %'[Teams Weight], 50)
		formatString: 0
		lineageTag: f7cd96af-faf4-4c6f-8a46-882ad39b10c3

	column 'Teams Weight'
		formatString: 0
		lineageTag: c04d441c-6e4c-4c40-bf32-ea7640001c21
		summarizeBy: none
		sourceColumn: [Value]

		extendedProperty ParameterMetadata =
				{
				  "version": 0
				}

		annotation SummarizationSetBy = User

	partition 'Teams Weight %' = calculated
		mode: import
		source = GENERATESERIES(0, 100, 1)

	annotation PBI_Id = 71712331e08941589848f7b241e70656

