table 'Word Weight %'
	lineageTag: f17e1703-d27b-4cc1-94f3-35cd13e1cbb6

	measure 'Word Weight % Value' = SELECTEDVALUE('Word Weight %'[Word Weight %], 10)
		formatString: 0
		lineageTag: 909a4f7d-990a-4a48-9f62-32c58bd8307d

	column 'Word Weight %'
		formatString: 0
		lineageTag: a502811c-e681-4100-b36e-eb33b049f492
		summarizeBy: none
		sourceColumn: [Value]

		extendedProperty ParameterMetadata =
				{
				  "version": 0
				}

		annotation SummarizationSetBy = User

	partition 'Word Weight %' = calculated
		mode: import
		source = GENERATESERIES(0, 100, 1)

	annotation PBI_Id = 8e92c2607e7946a1a4efcfa8eab30089

